/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Automation model module.
 * @module model/Automation
 * @version 0.1.0
 */
class Automation {
    /**
     * Constructs a new <code>Automation</code>.
     * @alias module:model/Automation
     * @param automationKey {String} 
     * @param config {Object} 
     * @param createdAt {Date} 
     * @param enabled {Boolean} 
     * @param tenantId {String} 
     * @param updatedAt {Date} 
     */
    constructor(automationKey, config, createdAt, enabled, tenantId, updatedAt) { 
        
        Automation.initialize(this, automationKey, config, createdAt, enabled, tenantId, updatedAt);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, automationKey, config, createdAt, enabled, tenantId, updatedAt) { 
        obj['automationKey'] = automationKey;
        obj['config'] = config;
        obj['createdAt'] = createdAt;
        obj['enabled'] = enabled;
        obj['tenantId'] = tenantId;
        obj['updatedAt'] = updatedAt;
    }

    /**
     * Constructs a <code>Automation</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Automation} obj Optional instance to populate.
     * @return {module:model/Automation} The populated <code>Automation</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Automation();

            if (data.hasOwnProperty('automationKey')) {
                obj['automationKey'] = ApiClient.convertToType(data['automationKey'], 'String');
            }
            if (data.hasOwnProperty('config')) {
                obj['config'] = ApiClient.convertToType(data['config'], Object);
            }
            if (data.hasOwnProperty('createdAt')) {
                obj['createdAt'] = ApiClient.convertToType(data['createdAt'], 'Date');
            }
            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('lastRunAt')) {
                obj['lastRunAt'] = ApiClient.convertToType(data['lastRunAt'], 'Date');
            }
            if (data.hasOwnProperty('nextRunAt')) {
                obj['nextRunAt'] = ApiClient.convertToType(data['nextRunAt'], 'Date');
            }
            if (data.hasOwnProperty('tenantId')) {
                obj['tenantId'] = ApiClient.convertToType(data['tenantId'], 'String');
            }
            if (data.hasOwnProperty('updatedAt')) {
                obj['updatedAt'] = ApiClient.convertToType(data['updatedAt'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Automation</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Automation</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Automation.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['automationKey'] && !(typeof data['automationKey'] === 'string' || data['automationKey'] instanceof String)) {
            throw new Error("Expected the field `automationKey` to be a primitive type in the JSON string but got " + data['automationKey']);
        }
        // ensure the json data is a string
        if (data['tenantId'] && !(typeof data['tenantId'] === 'string' || data['tenantId'] instanceof String)) {
            throw new Error("Expected the field `tenantId` to be a primitive type in the JSON string but got " + data['tenantId']);
        }

        return true;
    }


}

Automation.RequiredProperties = ["automationKey", "config", "createdAt", "enabled", "tenantId", "updatedAt"];

/**
 * @member {String} automationKey
 */
Automation.prototype['automationKey'] = undefined;

/**
 * @member {Object} config
 */
Automation.prototype['config'] = undefined;

/**
 * @member {Date} createdAt
 */
Automation.prototype['createdAt'] = undefined;

/**
 * @member {Boolean} enabled
 */
Automation.prototype['enabled'] = undefined;

/**
 * @member {Date} lastRunAt
 */
Automation.prototype['lastRunAt'] = undefined;

/**
 * @member {Date} nextRunAt
 */
Automation.prototype['nextRunAt'] = undefined;

/**
 * @member {String} tenantId
 */
Automation.prototype['tenantId'] = undefined;

/**
 * @member {Date} updatedAt
 */
Automation.prototype['updatedAt'] = undefined;






export default Automation;

