/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BankLookup model module.
 * @module model/BankLookup
 * @version 0.1.0
 */
class BankLookup {
    /**
     * Constructs a new <code>BankLookup</code>.
     * @alias module:model/BankLookup
     * @param iban {String} 
     * @param psd2Supported {Boolean} 
     */
    constructor(iban, psd2Supported) { 
        
        BankLookup.initialize(this, iban, psd2Supported);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, iban, psd2Supported) { 
        obj['iban'] = iban;
        obj['psd2_supported'] = psd2Supported;
    }

    /**
     * Constructs a <code>BankLookup</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BankLookup} obj Optional instance to populate.
     * @return {module:model/BankLookup} The populated <code>BankLookup</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BankLookup();

            if (data.hasOwnProperty('bank_name')) {
                obj['bank_name'] = ApiClient.convertToType(data['bank_name'], 'String');
            }
            if (data.hasOwnProperty('bic')) {
                obj['bic'] = ApiClient.convertToType(data['bic'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('nextgenpsd2_url')) {
                obj['nextgenpsd2_url'] = ApiClient.convertToType(data['nextgenpsd2_url'], 'String');
            }
            if (data.hasOwnProperty('psd2_supported')) {
                obj['psd2_supported'] = ApiClient.convertToType(data['psd2_supported'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BankLookup</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BankLookup</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BankLookup.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bank_name'] && !(typeof data['bank_name'] === 'string' || data['bank_name'] instanceof String)) {
            throw new Error("Expected the field `bank_name` to be a primitive type in the JSON string but got " + data['bank_name']);
        }
        // ensure the json data is a string
        if (data['bic'] && !(typeof data['bic'] === 'string' || data['bic'] instanceof String)) {
            throw new Error("Expected the field `bic` to be a primitive type in the JSON string but got " + data['bic']);
        }
        // ensure the json data is a string
        if (data['iban'] && !(typeof data['iban'] === 'string' || data['iban'] instanceof String)) {
            throw new Error("Expected the field `iban` to be a primitive type in the JSON string but got " + data['iban']);
        }
        // ensure the json data is a string
        if (data['nextgenpsd2_url'] && !(typeof data['nextgenpsd2_url'] === 'string' || data['nextgenpsd2_url'] instanceof String)) {
            throw new Error("Expected the field `nextgenpsd2_url` to be a primitive type in the JSON string but got " + data['nextgenpsd2_url']);
        }

        return true;
    }


}

BankLookup.RequiredProperties = ["iban", "psd2_supported"];

/**
 * @member {String} bank_name
 */
BankLookup.prototype['bank_name'] = undefined;

/**
 * @member {String} bic
 */
BankLookup.prototype['bic'] = undefined;

/**
 * @member {String} iban
 */
BankLookup.prototype['iban'] = undefined;

/**
 * @member {String} nextgenpsd2_url
 */
BankLookup.prototype['nextgenpsd2_url'] = undefined;

/**
 * @member {Boolean} psd2_supported
 */
BankLookup.prototype['psd2_supported'] = undefined;






export default BankLookup;

