/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BomStatus from './BomStatus';

/**
 * The BomUpdate model module.
 * @module model/BomUpdate
 * @version 0.1.0
 */
class BomUpdate {
    /**
     * Constructs a new <code>BomUpdate</code>.
     * @alias module:model/BomUpdate
     */
    constructor() { 
        
        BomUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BomUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BomUpdate} obj Optional instance to populate.
     * @return {module:model/BomUpdate} The populated <code>BomUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BomUpdate();

            if (data.hasOwnProperty('components')) {
                obj['components'] = ApiClient.convertToType(data['components'], Object);
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('outputQuantity')) {
                obj['outputQuantity'] = ApiClient.convertToType(data['outputQuantity'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], BomStatus);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BomUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BomUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['productId'] && !(typeof data['productId'] === 'string' || data['productId'] instanceof String)) {
            throw new Error("Expected the field `productId` to be a primitive type in the JSON string but got " + data['productId']);
        }

        return true;
    }


}



/**
 * JSON array of `{product_id, name, quantity, unit, scrap_rate}`.
 * @member {Object} components
 */
BomUpdate.prototype['components'] = undefined;

/**
 * @member {String} description
 */
BomUpdate.prototype['description'] = undefined;

/**
 * @member {String} name
 */
BomUpdate.prototype['name'] = undefined;

/**
 * Output quantity per production run (defaults to 1).
 * @member {Number} outputQuantity
 */
BomUpdate.prototype['outputQuantity'] = undefined;

/**
 * The finished product this BOM produces. References the product entity.
 * @member {String} productId
 */
BomUpdate.prototype['productId'] = undefined;

/**
 * One of: draft | active | archived
 * @member {module:model/BomStatus} status
 */
BomUpdate.prototype['status'] = undefined;






export default BomUpdate;

