/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BudgetKategorie model module.
 * @module model/BudgetKategorie
 * @version 0.1.0
 */
class BudgetKategorie {
    /**
     * Constructs a new <code>BudgetKategorie</code>.
     * @alias module:model/BudgetKategorie
     * @param budget {String} 
     * @param differenz {String} 
     * @param ist {String} 
     * @param kategorie {String} 
     */
    constructor(budget, differenz, ist, kategorie) { 
        
        BudgetKategorie.initialize(this, budget, differenz, ist, kategorie);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, budget, differenz, ist, kategorie) { 
        obj['budget'] = budget;
        obj['differenz'] = differenz;
        obj['ist'] = ist;
        obj['kategorie'] = kategorie;
    }

    /**
     * Constructs a <code>BudgetKategorie</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BudgetKategorie} obj Optional instance to populate.
     * @return {module:model/BudgetKategorie} The populated <code>BudgetKategorie</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BudgetKategorie();

            if (data.hasOwnProperty('budget')) {
                obj['budget'] = ApiClient.convertToType(data['budget'], 'String');
            }
            if (data.hasOwnProperty('differenz')) {
                obj['differenz'] = ApiClient.convertToType(data['differenz'], 'String');
            }
            if (data.hasOwnProperty('goal')) {
                obj['goal'] = ApiClient.convertToType(data['goal'], 'String');
            }
            if (data.hasOwnProperty('ist')) {
                obj['ist'] = ApiClient.convertToType(data['ist'], 'String');
            }
            if (data.hasOwnProperty('kategorie')) {
                obj['kategorie'] = ApiClient.convertToType(data['kategorie'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BudgetKategorie</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BudgetKategorie</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BudgetKategorie.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['budget'] && !(typeof data['budget'] === 'string' || data['budget'] instanceof String)) {
            throw new Error("Expected the field `budget` to be a primitive type in the JSON string but got " + data['budget']);
        }
        // ensure the json data is a string
        if (data['differenz'] && !(typeof data['differenz'] === 'string' || data['differenz'] instanceof String)) {
            throw new Error("Expected the field `differenz` to be a primitive type in the JSON string but got " + data['differenz']);
        }
        // ensure the json data is a string
        if (data['goal'] && !(typeof data['goal'] === 'string' || data['goal'] instanceof String)) {
            throw new Error("Expected the field `goal` to be a primitive type in the JSON string but got " + data['goal']);
        }
        // ensure the json data is a string
        if (data['ist'] && !(typeof data['ist'] === 'string' || data['ist'] instanceof String)) {
            throw new Error("Expected the field `ist` to be a primitive type in the JSON string but got " + data['ist']);
        }
        // ensure the json data is a string
        if (data['kategorie'] && !(typeof data['kategorie'] === 'string' || data['kategorie'] instanceof String)) {
            throw new Error("Expected the field `kategorie` to be a primitive type in the JSON string but got " + data['kategorie']);
        }

        return true;
    }


}

BudgetKategorie.RequiredProperties = ["budget", "differenz", "ist", "kategorie"];

/**
 * @member {String} budget
 */
BudgetKategorie.prototype['budget'] = undefined;

/**
 * @member {String} differenz
 */
BudgetKategorie.prototype['differenz'] = undefined;

/**
 * User-set monthly goal for the category, if any.
 * @member {String} goal
 */
BudgetKategorie.prototype['goal'] = undefined;

/**
 * @member {String} ist
 */
BudgetKategorie.prototype['ist'] = undefined;

/**
 * @member {String} kategorie
 */
BudgetKategorie.prototype['kategorie'] = undefined;






export default BudgetKategorie;

