/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BWAExpenses from './BWAExpenses';
import BWARevenue from './BWARevenue';
import BWASummary from './BWASummary';

/**
 * The BWAReport model module.
 * @module model/BWAReport
 * @version 0.1.0
 */
class BWAReport {
    /**
     * Constructs a new <code>BWAReport</code>.
     * @alias module:model/BWAReport
     * @param expenses {module:model/BWAExpenses} 
     * @param generatedAt {String} 
     * @param period {String} 
     * @param revenue {module:model/BWARevenue} 
     * @param summary {module:model/BWASummary} 
     */
    constructor(expenses, generatedAt, period, revenue, summary) { 
        
        BWAReport.initialize(this, expenses, generatedAt, period, revenue, summary);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, expenses, generatedAt, period, revenue, summary) { 
        obj['expenses'] = expenses;
        obj['generated_at'] = generatedAt;
        obj['period'] = period;
        obj['revenue'] = revenue;
        obj['summary'] = summary;
    }

    /**
     * Constructs a <code>BWAReport</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BWAReport} obj Optional instance to populate.
     * @return {module:model/BWAReport} The populated <code>BWAReport</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BWAReport();

            if (data.hasOwnProperty('expenses')) {
                obj['expenses'] = BWAExpenses.constructFromObject(data['expenses']);
            }
            if (data.hasOwnProperty('generated_at')) {
                obj['generated_at'] = ApiClient.convertToType(data['generated_at'], 'String');
            }
            if (data.hasOwnProperty('period')) {
                obj['period'] = ApiClient.convertToType(data['period'], 'String');
            }
            if (data.hasOwnProperty('revenue')) {
                obj['revenue'] = BWARevenue.constructFromObject(data['revenue']);
            }
            if (data.hasOwnProperty('summary')) {
                obj['summary'] = BWASummary.constructFromObject(data['summary']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BWAReport</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BWAReport</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BWAReport.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // validate the optional field `expenses`
        if (data['expenses']) { // data not null
          BWAExpenses.validateJSON(data['expenses']);
        }
        // ensure the json data is a string
        if (data['generated_at'] && !(typeof data['generated_at'] === 'string' || data['generated_at'] instanceof String)) {
            throw new Error("Expected the field `generated_at` to be a primitive type in the JSON string but got " + data['generated_at']);
        }
        // ensure the json data is a string
        if (data['period'] && !(typeof data['period'] === 'string' || data['period'] instanceof String)) {
            throw new Error("Expected the field `period` to be a primitive type in the JSON string but got " + data['period']);
        }
        // validate the optional field `revenue`
        if (data['revenue']) { // data not null
          BWARevenue.validateJSON(data['revenue']);
        }
        // validate the optional field `summary`
        if (data['summary']) { // data not null
          BWASummary.validateJSON(data['summary']);
        }

        return true;
    }


}

BWAReport.RequiredProperties = ["expenses", "generated_at", "period", "revenue", "summary"];

/**
 * @member {module:model/BWAExpenses} expenses
 */
BWAReport.prototype['expenses'] = undefined;

/**
 * @member {String} generated_at
 */
BWAReport.prototype['generated_at'] = undefined;

/**
 * @member {String} period
 */
BWAReport.prototype['period'] = undefined;

/**
 * @member {module:model/BWARevenue} revenue
 */
BWAReport.prototype['revenue'] = undefined;

/**
 * @member {module:model/BWASummary} summary
 */
BWAReport.prototype['summary'] = undefined;






export default BWAReport;

