/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BWASummary model module.
 * @module model/BWASummary
 * @version 0.1.0
 */
class BWASummary {
    /**
     * Constructs a new <code>BWASummary</code>.
     * @alias module:model/BWASummary
     * @param grossProfit {String} 
     * @param netProfit {String} 
     * @param openInvoicesCount {Number} 
     * @param openInvoicesTotal {String} 
     * @param overdueInvoicesCount {Number} 
     * @param overdueInvoicesTotal {String} 
     * @param profitMargin {Number} 
     */
    constructor(grossProfit, netProfit, openInvoicesCount, openInvoicesTotal, overdueInvoicesCount, overdueInvoicesTotal, profitMargin) { 
        
        BWASummary.initialize(this, grossProfit, netProfit, openInvoicesCount, openInvoicesTotal, overdueInvoicesCount, overdueInvoicesTotal, profitMargin);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, grossProfit, netProfit, openInvoicesCount, openInvoicesTotal, overdueInvoicesCount, overdueInvoicesTotal, profitMargin) { 
        obj['gross_profit'] = grossProfit;
        obj['net_profit'] = netProfit;
        obj['open_invoices_count'] = openInvoicesCount;
        obj['open_invoices_total'] = openInvoicesTotal;
        obj['overdue_invoices_count'] = overdueInvoicesCount;
        obj['overdue_invoices_total'] = overdueInvoicesTotal;
        obj['profit_margin'] = profitMargin;
    }

    /**
     * Constructs a <code>BWASummary</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BWASummary} obj Optional instance to populate.
     * @return {module:model/BWASummary} The populated <code>BWASummary</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BWASummary();

            if (data.hasOwnProperty('gross_profit')) {
                obj['gross_profit'] = ApiClient.convertToType(data['gross_profit'], 'String');
            }
            if (data.hasOwnProperty('net_profit')) {
                obj['net_profit'] = ApiClient.convertToType(data['net_profit'], 'String');
            }
            if (data.hasOwnProperty('open_invoices_count')) {
                obj['open_invoices_count'] = ApiClient.convertToType(data['open_invoices_count'], 'Number');
            }
            if (data.hasOwnProperty('open_invoices_total')) {
                obj['open_invoices_total'] = ApiClient.convertToType(data['open_invoices_total'], 'String');
            }
            if (data.hasOwnProperty('overdue_invoices_count')) {
                obj['overdue_invoices_count'] = ApiClient.convertToType(data['overdue_invoices_count'], 'Number');
            }
            if (data.hasOwnProperty('overdue_invoices_total')) {
                obj['overdue_invoices_total'] = ApiClient.convertToType(data['overdue_invoices_total'], 'String');
            }
            if (data.hasOwnProperty('profit_margin')) {
                obj['profit_margin'] = ApiClient.convertToType(data['profit_margin'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BWASummary</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BWASummary</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BWASummary.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['gross_profit'] && !(typeof data['gross_profit'] === 'string' || data['gross_profit'] instanceof String)) {
            throw new Error("Expected the field `gross_profit` to be a primitive type in the JSON string but got " + data['gross_profit']);
        }
        // ensure the json data is a string
        if (data['net_profit'] && !(typeof data['net_profit'] === 'string' || data['net_profit'] instanceof String)) {
            throw new Error("Expected the field `net_profit` to be a primitive type in the JSON string but got " + data['net_profit']);
        }
        // ensure the json data is a string
        if (data['open_invoices_total'] && !(typeof data['open_invoices_total'] === 'string' || data['open_invoices_total'] instanceof String)) {
            throw new Error("Expected the field `open_invoices_total` to be a primitive type in the JSON string but got " + data['open_invoices_total']);
        }
        // ensure the json data is a string
        if (data['overdue_invoices_total'] && !(typeof data['overdue_invoices_total'] === 'string' || data['overdue_invoices_total'] instanceof String)) {
            throw new Error("Expected the field `overdue_invoices_total` to be a primitive type in the JSON string but got " + data['overdue_invoices_total']);
        }

        return true;
    }


}

BWASummary.RequiredProperties = ["gross_profit", "net_profit", "open_invoices_count", "open_invoices_total", "overdue_invoices_count", "overdue_invoices_total", "profit_margin"];

/**
 * @member {String} gross_profit
 */
BWASummary.prototype['gross_profit'] = undefined;

/**
 * @member {String} net_profit
 */
BWASummary.prototype['net_profit'] = undefined;

/**
 * @member {Number} open_invoices_count
 */
BWASummary.prototype['open_invoices_count'] = undefined;

/**
 * @member {String} open_invoices_total
 */
BWASummary.prototype['open_invoices_total'] = undefined;

/**
 * @member {Number} overdue_invoices_count
 */
BWASummary.prototype['overdue_invoices_count'] = undefined;

/**
 * @member {String} overdue_invoices_total
 */
BWASummary.prototype['overdue_invoices_total'] = undefined;

/**
 * @member {Number} profit_margin
 */
BWASummary.prototype['profit_margin'] = undefined;






export default BWASummary;

