/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ComplianceEntry model module.
 * @module model/ComplianceEntry
 * @version 0.1.0
 */
class ComplianceEntry {
    /**
     * Constructs a new <code>ComplianceEntry</code>.
     * @alias module:model/ComplianceEntry
     * @param description {String} 
     * @param module {String} 
     * @param regulations {Array.<String>} 
     */
    constructor(description, module, regulations) { 
        
        ComplianceEntry.initialize(this, description, module, regulations);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, module, regulations) { 
        obj['description'] = description;
        obj['module'] = module;
        obj['regulations'] = regulations;
    }

    /**
     * Constructs a <code>ComplianceEntry</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComplianceEntry} obj Optional instance to populate.
     * @return {module:model/ComplianceEntry} The populated <code>ComplianceEntry</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComplianceEntry();

            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('module')) {
                obj['module'] = ApiClient.convertToType(data['module'], 'String');
            }
            if (data.hasOwnProperty('regulations')) {
                obj['regulations'] = ApiClient.convertToType(data['regulations'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ComplianceEntry</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ComplianceEntry</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ComplianceEntry.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['module'] && !(typeof data['module'] === 'string' || data['module'] instanceof String)) {
            throw new Error("Expected the field `module` to be a primitive type in the JSON string but got " + data['module']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['regulations'])) {
            throw new Error("Expected the field `regulations` to be an array in the JSON data but got " + data['regulations']);
        }

        return true;
    }


}

ComplianceEntry.RequiredProperties = ["description", "module", "regulations"];

/**
 * @member {String} description
 */
ComplianceEntry.prototype['description'] = undefined;

/**
 * @member {String} module
 */
ComplianceEntry.prototype['module'] = undefined;

/**
 * @member {Array.<String>} regulations
 */
ComplianceEntry.prototype['regulations'] = undefined;






export default ComplianceEntry;

