/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrainingSource from './TrainingSource';

/**
 * The ComplianceTrainingCreate model module.
 * @module model/ComplianceTrainingCreate
 * @version 0.1.0
 */
class ComplianceTrainingCreate {
    /**
     * Constructs a new <code>ComplianceTrainingCreate</code>.
     * @alias module:model/ComplianceTrainingCreate
     */
    constructor() { 
        
        ComplianceTrainingCreate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ComplianceTrainingCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ComplianceTrainingCreate} obj Optional instance to populate.
     * @return {module:model/ComplianceTrainingCreate} The populated <code>ComplianceTrainingCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ComplianceTrainingCreate();

            if (data.hasOwnProperty('assignable')) {
                obj['assignable'] = ApiClient.convertToType(data['assignable'], 'Boolean');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('passScore')) {
                obj['passScore'] = ApiClient.convertToType(data['passScore'], 'Number');
            }
            if (data.hasOwnProperty('pluginPlatform')) {
                obj['pluginPlatform'] = ApiClient.convertToType(data['pluginPlatform'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = TrainingSource.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('validityMonths')) {
                obj['validityMonths'] = ApiClient.convertToType(data['validityMonths'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ComplianceTrainingCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ComplianceTrainingCreate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['pluginPlatform'] && !(typeof data['pluginPlatform'] === 'string' || data['pluginPlatform'] instanceof String)) {
            throw new Error("Expected the field `pluginPlatform` to be a primitive type in the JSON string but got " + data['pluginPlatform']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}



/**
 * Whether HR can assign this training as required for employees.
 * @member {Boolean} assignable
 */
ComplianceTrainingCreate.prototype['assignable'] = undefined;

/**
 * Stable code used by plugins and frontend players (e.g. \"data_privacy\").
 * @member {String} code
 */
ComplianceTrainingCreate.prototype['code'] = undefined;

/**
 * @member {String} description
 */
ComplianceTrainingCreate.prototype['description'] = undefined;

/**
 * Minimum score (0–100) required to pass.
 * @member {Number} passScore
 */
ComplianceTrainingCreate.prototype['passScore'] = undefined;

/**
 * Marketplace plugin platform id when source = Plugin.
 * @member {String} pluginPlatform
 */
ComplianceTrainingCreate.prototype['pluginPlatform'] = undefined;

/**
 * @member {module:model/TrainingSource} source
 */
ComplianceTrainingCreate.prototype['source'] = undefined;

/**
 * @member {String} title
 */
ComplianceTrainingCreate.prototype['title'] = undefined;

/**
 * Certificate validity in months; null = no expiry.
 * @member {Number} validityMonths
 */
ComplianceTrainingCreate.prototype['validityMonths'] = undefined;






export default ComplianceTrainingCreate;

