/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ContactInfo model module.
 * @module model/ContactInfo
 * @version 0.1.0
 */
class ContactInfo {
    /**
     * Constructs a new <code>ContactInfo</code>.
     * @alias module:model/ContactInfo
     * @param hint {String} 
     * @param hintEn {String} 
     * @param role {String} 
     * @param roleEn {String} 
     */
    constructor(hint, hintEn, role, roleEn) { 
        
        ContactInfo.initialize(this, hint, hintEn, role, roleEn);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hint, hintEn, role, roleEn) { 
        obj['hint'] = hint;
        obj['hintEn'] = hintEn;
        obj['role'] = role;
        obj['roleEn'] = roleEn;
    }

    /**
     * Constructs a <code>ContactInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ContactInfo} obj Optional instance to populate.
     * @return {module:model/ContactInfo} The populated <code>ContactInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ContactInfo();

            if (data.hasOwnProperty('hint')) {
                obj['hint'] = ApiClient.convertToType(data['hint'], 'String');
            }
            if (data.hasOwnProperty('hintEn')) {
                obj['hintEn'] = ApiClient.convertToType(data['hintEn'], 'String');
            }
            if (data.hasOwnProperty('role')) {
                obj['role'] = ApiClient.convertToType(data['role'], 'String');
            }
            if (data.hasOwnProperty('roleEn')) {
                obj['roleEn'] = ApiClient.convertToType(data['roleEn'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ContactInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ContactInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ContactInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hint'] && !(typeof data['hint'] === 'string' || data['hint'] instanceof String)) {
            throw new Error("Expected the field `hint` to be a primitive type in the JSON string but got " + data['hint']);
        }
        // ensure the json data is a string
        if (data['hintEn'] && !(typeof data['hintEn'] === 'string' || data['hintEn'] instanceof String)) {
            throw new Error("Expected the field `hintEn` to be a primitive type in the JSON string but got " + data['hintEn']);
        }
        // ensure the json data is a string
        if (data['role'] && !(typeof data['role'] === 'string' || data['role'] instanceof String)) {
            throw new Error("Expected the field `role` to be a primitive type in the JSON string but got " + data['role']);
        }
        // ensure the json data is a string
        if (data['roleEn'] && !(typeof data['roleEn'] === 'string' || data['roleEn'] instanceof String)) {
            throw new Error("Expected the field `roleEn` to be a primitive type in the JSON string but got " + data['roleEn']);
        }

        return true;
    }


}

ContactInfo.RequiredProperties = ["hint", "hintEn", "role", "roleEn"];

/**
 * @member {String} hint
 */
ContactInfo.prototype['hint'] = undefined;

/**
 * @member {String} hintEn
 */
ContactInfo.prototype['hintEn'] = undefined;

/**
 * @member {String} role
 */
ContactInfo.prototype['role'] = undefined;

/**
 * @member {String} roleEn
 */
ContactInfo.prototype['roleEn'] = undefined;






export default ContactInfo;

