/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CostingLine model module.
 * @module model/CostingLine
 * @version 0.1.0
 */
class CostingLine {
    /**
     * Constructs a new <code>CostingLine</code>.
     * A single costing line: material cost for one BOM component.
     * @alias module:model/CostingLine
     * @param lineCost {String} total_quantity × unit_purchase_price (0 when price unknown).
     * @param name {String} 
     * @param productId {String} 
     * @param quantityPerUnit {Number} Component quantity required per finished unit.
     * @param sku {String} 
     * @param totalQuantity {Number} Total component quantity consumed by this order.
     */
    constructor(lineCost, name, productId, quantityPerUnit, sku, totalQuantity) { 
        
        CostingLine.initialize(this, lineCost, name, productId, quantityPerUnit, sku, totalQuantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lineCost, name, productId, quantityPerUnit, sku, totalQuantity) { 
        obj['lineCost'] = lineCost;
        obj['name'] = name;
        obj['productId'] = productId;
        obj['quantityPerUnit'] = quantityPerUnit;
        obj['sku'] = sku;
        obj['totalQuantity'] = totalQuantity;
    }

    /**
     * Constructs a <code>CostingLine</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CostingLine} obj Optional instance to populate.
     * @return {module:model/CostingLine} The populated <code>CostingLine</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CostingLine();

            if (data.hasOwnProperty('lineCost')) {
                obj['lineCost'] = ApiClient.convertToType(data['lineCost'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('quantityPerUnit')) {
                obj['quantityPerUnit'] = ApiClient.convertToType(data['quantityPerUnit'], 'Number');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('totalQuantity')) {
                obj['totalQuantity'] = ApiClient.convertToType(data['totalQuantity'], 'Number');
            }
            if (data.hasOwnProperty('unitPurchasePrice')) {
                obj['unitPurchasePrice'] = ApiClient.convertToType(data['unitPurchasePrice'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CostingLine</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CostingLine</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CostingLine.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['lineCost'] && !(typeof data['lineCost'] === 'string' || data['lineCost'] instanceof String)) {
            throw new Error("Expected the field `lineCost` to be a primitive type in the JSON string but got " + data['lineCost']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['productId'] && !(typeof data['productId'] === 'string' || data['productId'] instanceof String)) {
            throw new Error("Expected the field `productId` to be a primitive type in the JSON string but got " + data['productId']);
        }
        // ensure the json data is a string
        if (data['sku'] && !(typeof data['sku'] === 'string' || data['sku'] instanceof String)) {
            throw new Error("Expected the field `sku` to be a primitive type in the JSON string but got " + data['sku']);
        }
        // ensure the json data is a string
        if (data['unitPurchasePrice'] && !(typeof data['unitPurchasePrice'] === 'string' || data['unitPurchasePrice'] instanceof String)) {
            throw new Error("Expected the field `unitPurchasePrice` to be a primitive type in the JSON string but got " + data['unitPurchasePrice']);
        }

        return true;
    }


}

CostingLine.RequiredProperties = ["lineCost", "name", "productId", "quantityPerUnit", "sku", "totalQuantity"];

/**
 * total_quantity × unit_purchase_price (0 when price unknown).
 * @member {String} lineCost
 */
CostingLine.prototype['lineCost'] = undefined;

/**
 * @member {String} name
 */
CostingLine.prototype['name'] = undefined;

/**
 * @member {String} productId
 */
CostingLine.prototype['productId'] = undefined;

/**
 * Component quantity required per finished unit.
 * @member {Number} quantityPerUnit
 */
CostingLine.prototype['quantityPerUnit'] = undefined;

/**
 * @member {String} sku
 */
CostingLine.prototype['sku'] = undefined;

/**
 * Total component quantity consumed by this order.
 * @member {Number} totalQuantity
 */
CostingLine.prototype['totalQuantity'] = undefined;

/**
 * @member {String} unitPurchasePrice
 */
CostingLine.prototype['unitPurchasePrice'] = undefined;






export default CostingLine;

