/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DeclarationType from './DeclarationType';

/**
 * The Declaration model module.
 * @module model/Declaration
 * @version 0.1.0
 */
class Declaration {
    /**
     * Constructs a new <code>Declaration</code>.
     * @alias module:model/Declaration
     */
    constructor() { 
        
        Declaration.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Declaration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Declaration} obj Optional instance to populate.
     * @return {module:model/Declaration} The populated <code>Declaration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Declaration();

            if (data.hasOwnProperty('declarationType')) {
                obj['declarationType'] = ApiClient.convertToType(data['declarationType'], DeclarationType);
            }
            if (data.hasOwnProperty('isCurrent')) {
                obj['isCurrent'] = ApiClient.convertToType(data['isCurrent'], 'Boolean');
            }
            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('validFrom')) {
                obj['validFrom'] = ApiClient.convertToType(data['validFrom'], 'Date');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Declaration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Declaration</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }

        return true;
    }


}



/**
 * Art der Erklärung: \"dcgk\" (Entsprechenserklärung § 161 AktG) oder \"unternehmensfuehrung\" (Erklärung zur Unternehmensführung § 289f HGB).
 * @member {module:model/DeclarationType} declarationType
 */
Declaration.prototype['declarationType'] = undefined;

/**
 * Kennzeichnet die aktuell gültige Fassung (max. eine je Mandant).
 * @member {Boolean} isCurrent
 */
Declaration.prototype['isCurrent'] = undefined;

/**
 * Inhalt der Erklärung als Markdown.
 * @member {String} text
 */
Declaration.prototype['text'] = undefined;

/**
 * Datum, ab dem die Erklärung gilt.
 * @member {Date} validFrom
 */
Declaration.prototype['validFrom'] = undefined;

/**
 * Versionsbezeichnung der Erklärung (z.B. \"2025-01\").
 * @member {String} version
 */
Declaration.prototype['version'] = undefined;






export default Declaration;

