/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The EmissionFactorResponse model module.
 * @module model/EmissionFactorResponse
 * @version 0.1.0
 */
class EmissionFactorResponse {
    /**
     * Constructs a new <code>EmissionFactorResponse</code>.
     * @alias module:model/EmissionFactorResponse
     * @param categoryId {String} 
     * @param kgCo2ePerUnit {Number} 
     * @param nameDe {String} 
     * @param source {String} 
     * @param unit {String} 
     * @param version {String} 
     */
    constructor(categoryId, kgCo2ePerUnit, nameDe, source, unit, version) { 
        
        EmissionFactorResponse.initialize(this, categoryId, kgCo2ePerUnit, nameDe, source, unit, version);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, categoryId, kgCo2ePerUnit, nameDe, source, unit, version) { 
        obj['category_id'] = categoryId;
        obj['kg_co2e_per_unit'] = kgCo2ePerUnit;
        obj['name_de'] = nameDe;
        obj['source'] = source;
        obj['unit'] = unit;
        obj['version'] = version;
    }

    /**
     * Constructs a <code>EmissionFactorResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmissionFactorResponse} obj Optional instance to populate.
     * @return {module:model/EmissionFactorResponse} The populated <code>EmissionFactorResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmissionFactorResponse();

            if (data.hasOwnProperty('category_id')) {
                obj['category_id'] = ApiClient.convertToType(data['category_id'], 'String');
            }
            if (data.hasOwnProperty('kg_co2e_per_unit')) {
                obj['kg_co2e_per_unit'] = ApiClient.convertToType(data['kg_co2e_per_unit'], 'Number');
            }
            if (data.hasOwnProperty('name_de')) {
                obj['name_de'] = ApiClient.convertToType(data['name_de'], 'String');
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = ApiClient.convertToType(data['source'], 'String');
            }
            if (data.hasOwnProperty('unit')) {
                obj['unit'] = ApiClient.convertToType(data['unit'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmissionFactorResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmissionFactorResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of EmissionFactorResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['category_id'] && !(typeof data['category_id'] === 'string' || data['category_id'] instanceof String)) {
            throw new Error("Expected the field `category_id` to be a primitive type in the JSON string but got " + data['category_id']);
        }
        // ensure the json data is a string
        if (data['name_de'] && !(typeof data['name_de'] === 'string' || data['name_de'] instanceof String)) {
            throw new Error("Expected the field `name_de` to be a primitive type in the JSON string but got " + data['name_de']);
        }
        // ensure the json data is a string
        if (data['source'] && !(typeof data['source'] === 'string' || data['source'] instanceof String)) {
            throw new Error("Expected the field `source` to be a primitive type in the JSON string but got " + data['source']);
        }
        // ensure the json data is a string
        if (data['unit'] && !(typeof data['unit'] === 'string' || data['unit'] instanceof String)) {
            throw new Error("Expected the field `unit` to be a primitive type in the JSON string but got " + data['unit']);
        }
        // ensure the json data is a string
        if (data['version'] && !(typeof data['version'] === 'string' || data['version'] instanceof String)) {
            throw new Error("Expected the field `version` to be a primitive type in the JSON string but got " + data['version']);
        }

        return true;
    }


}

EmissionFactorResponse.RequiredProperties = ["category_id", "kg_co2e_per_unit", "name_de", "source", "unit", "version"];

/**
 * @member {String} category_id
 */
EmissionFactorResponse.prototype['category_id'] = undefined;

/**
 * @member {Number} kg_co2e_per_unit
 */
EmissionFactorResponse.prototype['kg_co2e_per_unit'] = undefined;

/**
 * @member {String} name_de
 */
EmissionFactorResponse.prototype['name_de'] = undefined;

/**
 * @member {String} source
 */
EmissionFactorResponse.prototype['source'] = undefined;

/**
 * @member {String} unit
 */
EmissionFactorResponse.prototype['unit'] = undefined;

/**
 * @member {String} version
 */
EmissionFactorResponse.prototype['version'] = undefined;






export default EmissionFactorResponse;

