/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CountryCode from './CountryCode';
import EmployeeStatus from './EmployeeStatus';
import Gender from './Gender';

/**
 * The EmployeeUpdate model module.
 * @module model/EmployeeUpdate
 * @version 0.1.0
 */
class EmployeeUpdate {
    /**
     * Constructs a new <code>EmployeeUpdate</code>.
     * @alias module:model/EmployeeUpdate
     */
    constructor() { 
        
        EmployeeUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EmployeeUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmployeeUpdate} obj Optional instance to populate.
     * @return {module:model/EmployeeUpdate} The populated <code>EmployeeUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmployeeUpdate();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('backupEmployeeId')) {
                obj['backupEmployeeId'] = ApiClient.convertToType(data['backupEmployeeId'], 'String');
            }
            if (data.hasOwnProperty('bic')) {
                obj['bic'] = ApiClient.convertToType(data['bic'], 'String');
            }
            if (data.hasOwnProperty('city')) {
                obj['city'] = ApiClient.convertToType(data['city'], 'String');
            }
            if (data.hasOwnProperty('country')) {
                obj['country'] = ApiClient.convertToType(data['country'], CountryCode);
            }
            if (data.hasOwnProperty('dateOfBirth')) {
                obj['dateOfBirth'] = ApiClient.convertToType(data['dateOfBirth'], 'Date');
            }
            if (data.hasOwnProperty('departmentId')) {
                obj['departmentId'] = ApiClient.convertToType(data['departmentId'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('firstName')) {
                obj['firstName'] = ApiClient.convertToType(data['firstName'], 'String');
            }
            if (data.hasOwnProperty('gender')) {
                obj['gender'] = ApiClient.convertToType(data['gender'], Gender);
            }
            if (data.hasOwnProperty('hireDate')) {
                obj['hireDate'] = ApiClient.convertToType(data['hireDate'], 'Date');
            }
            if (data.hasOwnProperty('hourlyCost')) {
                obj['hourlyCost'] = ApiClient.convertToType(data['hourlyCost'], 'String');
            }
            if (data.hasOwnProperty('iban')) {
                obj['iban'] = ApiClient.convertToType(data['iban'], 'String');
            }
            if (data.hasOwnProperty('jobTitle')) {
                obj['jobTitle'] = ApiClient.convertToType(data['jobTitle'], 'String');
            }
            if (data.hasOwnProperty('lastLogin')) {
                obj['lastLogin'] = ApiClient.convertToType(data['lastLogin'], 'Date');
            }
            if (data.hasOwnProperty('lastName')) {
                obj['lastName'] = ApiClient.convertToType(data['lastName'], 'String');
            }
            if (data.hasOwnProperty('lastUpdated')) {
                obj['lastUpdated'] = ApiClient.convertToType(data['lastUpdated'], 'Date');
            }
            if (data.hasOwnProperty('monthlySalary')) {
                obj['monthlySalary'] = ApiClient.convertToType(data['monthlySalary'], 'String');
            }
            if (data.hasOwnProperty('phone')) {
                obj['phone'] = ApiClient.convertToType(data['phone'], 'String');
            }
            if (data.hasOwnProperty('state')) {
                obj['state'] = ApiClient.convertToType(data['state'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], EmployeeStatus);
            }
            if (data.hasOwnProperty('userId')) {
                obj['userId'] = ApiClient.convertToType(data['userId'], 'String');
            }
            if (data.hasOwnProperty('weeklyHours')) {
                obj['weeklyHours'] = ApiClient.convertToType(data['weeklyHours'], 'String');
            }
            if (data.hasOwnProperty('zip')) {
                obj['zip'] = ApiClient.convertToType(data['zip'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EmployeeUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EmployeeUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['address'] && !(typeof data['address'] === 'string' || data['address'] instanceof String)) {
            throw new Error("Expected the field `address` to be a primitive type in the JSON string but got " + data['address']);
        }
        // ensure the json data is a string
        if (data['backupEmployeeId'] && !(typeof data['backupEmployeeId'] === 'string' || data['backupEmployeeId'] instanceof String)) {
            throw new Error("Expected the field `backupEmployeeId` to be a primitive type in the JSON string but got " + data['backupEmployeeId']);
        }
        // ensure the json data is a string
        if (data['bic'] && !(typeof data['bic'] === 'string' || data['bic'] instanceof String)) {
            throw new Error("Expected the field `bic` to be a primitive type in the JSON string but got " + data['bic']);
        }
        // ensure the json data is a string
        if (data['city'] && !(typeof data['city'] === 'string' || data['city'] instanceof String)) {
            throw new Error("Expected the field `city` to be a primitive type in the JSON string but got " + data['city']);
        }
        // ensure the json data is a string
        if (data['departmentId'] && !(typeof data['departmentId'] === 'string' || data['departmentId'] instanceof String)) {
            throw new Error("Expected the field `departmentId` to be a primitive type in the JSON string but got " + data['departmentId']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['firstName'] && !(typeof data['firstName'] === 'string' || data['firstName'] instanceof String)) {
            throw new Error("Expected the field `firstName` to be a primitive type in the JSON string but got " + data['firstName']);
        }
        // ensure the json data is a string
        if (data['hourlyCost'] && !(typeof data['hourlyCost'] === 'string' || data['hourlyCost'] instanceof String)) {
            throw new Error("Expected the field `hourlyCost` to be a primitive type in the JSON string but got " + data['hourlyCost']);
        }
        // ensure the json data is a string
        if (data['iban'] && !(typeof data['iban'] === 'string' || data['iban'] instanceof String)) {
            throw new Error("Expected the field `iban` to be a primitive type in the JSON string but got " + data['iban']);
        }
        // ensure the json data is a string
        if (data['jobTitle'] && !(typeof data['jobTitle'] === 'string' || data['jobTitle'] instanceof String)) {
            throw new Error("Expected the field `jobTitle` to be a primitive type in the JSON string but got " + data['jobTitle']);
        }
        // ensure the json data is a string
        if (data['lastName'] && !(typeof data['lastName'] === 'string' || data['lastName'] instanceof String)) {
            throw new Error("Expected the field `lastName` to be a primitive type in the JSON string but got " + data['lastName']);
        }
        // ensure the json data is a string
        if (data['monthlySalary'] && !(typeof data['monthlySalary'] === 'string' || data['monthlySalary'] instanceof String)) {
            throw new Error("Expected the field `monthlySalary` to be a primitive type in the JSON string but got " + data['monthlySalary']);
        }
        // ensure the json data is a string
        if (data['phone'] && !(typeof data['phone'] === 'string' || data['phone'] instanceof String)) {
            throw new Error("Expected the field `phone` to be a primitive type in the JSON string but got " + data['phone']);
        }
        // ensure the json data is a string
        if (data['state'] && !(typeof data['state'] === 'string' || data['state'] instanceof String)) {
            throw new Error("Expected the field `state` to be a primitive type in the JSON string but got " + data['state']);
        }
        // ensure the json data is a string
        if (data['userId'] && !(typeof data['userId'] === 'string' || data['userId'] instanceof String)) {
            throw new Error("Expected the field `userId` to be a primitive type in the JSON string but got " + data['userId']);
        }
        // ensure the json data is a string
        if (data['weeklyHours'] && !(typeof data['weeklyHours'] === 'string' || data['weeklyHours'] instanceof String)) {
            throw new Error("Expected the field `weeklyHours` to be a primitive type in the JSON string but got " + data['weeklyHours']);
        }
        // ensure the json data is a string
        if (data['zip'] && !(typeof data['zip'] === 'string' || data['zip'] instanceof String)) {
            throw new Error("Expected the field `zip` to be a primitive type in the JSON string but got " + data['zip']);
        }

        return true;
    }


}



/**
 * @member {String} address
 */
EmployeeUpdate.prototype['address'] = undefined;

/**
 * References another employee who covers when this employee is absent.
 * @member {String} backupEmployeeId
 */
EmployeeUpdate.prototype['backupEmployeeId'] = undefined;

/**
 * @member {String} bic
 */
EmployeeUpdate.prototype['bic'] = undefined;

/**
 * @member {String} city
 */
EmployeeUpdate.prototype['city'] = undefined;

/**
 * @member {module:model/CountryCode} country
 */
EmployeeUpdate.prototype['country'] = undefined;

/**
 * @member {Date} dateOfBirth
 */
EmployeeUpdate.prototype['dateOfBirth'] = undefined;

/**
 * References the department entity.
 * @member {String} departmentId
 */
EmployeeUpdate.prototype['departmentId'] = undefined;

/**
 * @member {String} email
 */
EmployeeUpdate.prototype['email'] = undefined;

/**
 * @member {String} firstName
 */
EmployeeUpdate.prototype['firstName'] = undefined;

/**
 * Gender for pay-transparency reporting: \"male\", \"female\" or \"diverse\".
 * @member {module:model/Gender} gender
 */
EmployeeUpdate.prototype['gender'] = undefined;

/**
 * @member {Date} hireDate
 */
EmployeeUpdate.prototype['hireDate'] = undefined;

/**
 * Hourly cost rate in EUR for labor-cost reporting; when unset the rate is derived from `monthly_salary / (weekly_hours * 4.33)`.
 * @member {String} hourlyCost
 */
EmployeeUpdate.prototype['hourlyCost'] = undefined;

/**
 * @member {String} iban
 */
EmployeeUpdate.prototype['iban'] = undefined;

/**
 * @member {String} jobTitle
 */
EmployeeUpdate.prototype['jobTitle'] = undefined;

/**
 * @member {Date} lastLogin
 */
EmployeeUpdate.prototype['lastLogin'] = undefined;

/**
 * @member {String} lastName
 */
EmployeeUpdate.prototype['lastName'] = undefined;

/**
 * @member {Date} lastUpdated
 */
EmployeeUpdate.prototype['lastUpdated'] = undefined;

/**
 * Gross monthly salary in EUR for pay-transparency reporting.
 * @member {String} monthlySalary
 */
EmployeeUpdate.prototype['monthlySalary'] = undefined;

/**
 * @member {String} phone
 */
EmployeeUpdate.prototype['phone'] = undefined;

/**
 * @member {String} state
 */
EmployeeUpdate.prototype['state'] = undefined;

/**
 * @member {module:model/EmployeeStatus} status
 */
EmployeeUpdate.prototype['status'] = undefined;

/**
 * References the user entity.
 * @member {String} userId
 */
EmployeeUpdate.prototype['userId'] = undefined;

/**
 * Contractual weekly working hours for pay-transparency normalization.
 * @member {String} weeklyHours
 */
EmployeeUpdate.prototype['weeklyHours'] = undefined;

/**
 * @member {String} zip
 */
EmployeeUpdate.prototype['zip'] = undefined;






export default EmployeeUpdate;

