/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The FristEintrag model module.
 * @module model/FristEintrag
 * @version 0.1.0
 */
class FristEintrag {
    /**
     * Constructs a new <code>FristEintrag</code>.
     * @alias module:model/FristEintrag
     * @param bezeichnung {String} 
     * @param faellig {String} 
     * @param faelligOriginal {String} 
     * @param typ {String} 
     * @param zeitraum {String} 
     */
    constructor(bezeichnung, faellig, faelligOriginal, typ, zeitraum) { 
        
        FristEintrag.initialize(this, bezeichnung, faellig, faelligOriginal, typ, zeitraum);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, bezeichnung, faellig, faelligOriginal, typ, zeitraum) { 
        obj['bezeichnung'] = bezeichnung;
        obj['faellig'] = faellig;
        obj['faellig_original'] = faelligOriginal;
        obj['typ'] = typ;
        obj['zeitraum'] = zeitraum;
    }

    /**
     * Constructs a <code>FristEintrag</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/FristEintrag} obj Optional instance to populate.
     * @return {module:model/FristEintrag} The populated <code>FristEintrag</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FristEintrag();

            if (data.hasOwnProperty('bezeichnung')) {
                obj['bezeichnung'] = ApiClient.convertToType(data['bezeichnung'], 'String');
            }
            if (data.hasOwnProperty('faellig')) {
                obj['faellig'] = ApiClient.convertToType(data['faellig'], 'String');
            }
            if (data.hasOwnProperty('faellig_original')) {
                obj['faellig_original'] = ApiClient.convertToType(data['faellig_original'], 'String');
            }
            if (data.hasOwnProperty('hinweis')) {
                obj['hinweis'] = ApiClient.convertToType(data['hinweis'], 'String');
            }
            if (data.hasOwnProperty('typ')) {
                obj['typ'] = ApiClient.convertToType(data['typ'], 'String');
            }
            if (data.hasOwnProperty('zeitraum')) {
                obj['zeitraum'] = ApiClient.convertToType(data['zeitraum'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>FristEintrag</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>FristEintrag</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of FristEintrag.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['bezeichnung'] && !(typeof data['bezeichnung'] === 'string' || data['bezeichnung'] instanceof String)) {
            throw new Error("Expected the field `bezeichnung` to be a primitive type in the JSON string but got " + data['bezeichnung']);
        }
        // ensure the json data is a string
        if (data['faellig'] && !(typeof data['faellig'] === 'string' || data['faellig'] instanceof String)) {
            throw new Error("Expected the field `faellig` to be a primitive type in the JSON string but got " + data['faellig']);
        }
        // ensure the json data is a string
        if (data['faellig_original'] && !(typeof data['faellig_original'] === 'string' || data['faellig_original'] instanceof String)) {
            throw new Error("Expected the field `faellig_original` to be a primitive type in the JSON string but got " + data['faellig_original']);
        }
        // ensure the json data is a string
        if (data['hinweis'] && !(typeof data['hinweis'] === 'string' || data['hinweis'] instanceof String)) {
            throw new Error("Expected the field `hinweis` to be a primitive type in the JSON string but got " + data['hinweis']);
        }
        // ensure the json data is a string
        if (data['typ'] && !(typeof data['typ'] === 'string' || data['typ'] instanceof String)) {
            throw new Error("Expected the field `typ` to be a primitive type in the JSON string but got " + data['typ']);
        }
        // ensure the json data is a string
        if (data['zeitraum'] && !(typeof data['zeitraum'] === 'string' || data['zeitraum'] instanceof String)) {
            throw new Error("Expected the field `zeitraum` to be a primitive type in the JSON string but got " + data['zeitraum']);
        }

        return true;
    }


}

FristEintrag.RequiredProperties = ["bezeichnung", "faellig", "faellig_original", "typ", "zeitraum"];

/**
 * @member {String} bezeichnung
 */
FristEintrag.prototype['bezeichnung'] = undefined;

/**
 * @member {String} faellig
 */
FristEintrag.prototype['faellig'] = undefined;

/**
 * @member {String} faellig_original
 */
FristEintrag.prototype['faellig_original'] = undefined;

/**
 * @member {String} hinweis
 */
FristEintrag.prototype['hinweis'] = undefined;

/**
 * @member {String} typ
 */
FristEintrag.prototype['typ'] = undefined;

/**
 * @member {String} zeitraum
 */
FristEintrag.prototype['zeitraum'] = undefined;






export default FristEintrag;

