/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HrTrainingOverview model module.
 * @module model/HrTrainingOverview
 * @version 0.1.0
 */
class HrTrainingOverview {
    /**
     * Constructs a new <code>HrTrainingOverview</code>.
     * @alias module:model/HrTrainingOverview
     * @param assignedCount {Number} 
     * @param code {String} 
     * @param completedCount {Number} 
     * @param overdueCount {Number} 
     * @param title {String} 
     * @param trainingId {String} 
     */
    constructor(assignedCount, code, completedCount, overdueCount, title, trainingId) { 
        
        HrTrainingOverview.initialize(this, assignedCount, code, completedCount, overdueCount, title, trainingId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, assignedCount, code, completedCount, overdueCount, title, trainingId) { 
        obj['assignedCount'] = assignedCount;
        obj['code'] = code;
        obj['completedCount'] = completedCount;
        obj['overdueCount'] = overdueCount;
        obj['title'] = title;
        obj['trainingId'] = trainingId;
    }

    /**
     * Constructs a <code>HrTrainingOverview</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HrTrainingOverview} obj Optional instance to populate.
     * @return {module:model/HrTrainingOverview} The populated <code>HrTrainingOverview</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HrTrainingOverview();

            if (data.hasOwnProperty('assignedCount')) {
                obj['assignedCount'] = ApiClient.convertToType(data['assignedCount'], 'Number');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('completedCount')) {
                obj['completedCount'] = ApiClient.convertToType(data['completedCount'], 'Number');
            }
            if (data.hasOwnProperty('overdueCount')) {
                obj['overdueCount'] = ApiClient.convertToType(data['overdueCount'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('trainingId')) {
                obj['trainingId'] = ApiClient.convertToType(data['trainingId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HrTrainingOverview</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HrTrainingOverview</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HrTrainingOverview.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['trainingId'] && !(typeof data['trainingId'] === 'string' || data['trainingId'] instanceof String)) {
            throw new Error("Expected the field `trainingId` to be a primitive type in the JSON string but got " + data['trainingId']);
        }

        return true;
    }


}

HrTrainingOverview.RequiredProperties = ["assignedCount", "code", "completedCount", "overdueCount", "title", "trainingId"];

/**
 * @member {Number} assignedCount
 */
HrTrainingOverview.prototype['assignedCount'] = undefined;

/**
 * @member {String} code
 */
HrTrainingOverview.prototype['code'] = undefined;

/**
 * @member {Number} completedCount
 */
HrTrainingOverview.prototype['completedCount'] = undefined;

/**
 * @member {Number} overdueCount
 */
HrTrainingOverview.prototype['overdueCount'] = undefined;

/**
 * @member {String} title
 */
HrTrainingOverview.prototype['title'] = undefined;

/**
 * @member {String} trainingId
 */
HrTrainingOverview.prototype['trainingId'] = undefined;






export default HrTrainingOverview;

