/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import InventoryCountStatus from './InventoryCountStatus';

/**
 * The InventoryCountCreate model module.
 * @module model/InventoryCountCreate
 * @version 0.1.0
 */
class InventoryCountCreate {
    /**
     * Constructs a new <code>InventoryCountCreate</code>.
     * @alias module:model/InventoryCountCreate
     * @param countDate {Date} 
     * @param countNumber {String} 
     * @param lineItems {Object} JSON array of `{product_id, name, sku, expected_quantity, counted_quantity, bin_location?, batch_number?, variance}`.
     * @param status {module:model/InventoryCountStatus} One of: draft | counting | reviewed | posted
     * @param warehouseId {String} References the warehouse entity.
     */
    constructor(countDate, countNumber, lineItems, status, warehouseId) { 
        
        InventoryCountCreate.initialize(this, countDate, countNumber, lineItems, status, warehouseId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, countDate, countNumber, lineItems, status, warehouseId) { 
        obj['countDate'] = countDate;
        obj['countNumber'] = countNumber;
        obj['lineItems'] = lineItems;
        obj['status'] = status;
        obj['warehouseId'] = warehouseId;
    }

    /**
     * Constructs a <code>InventoryCountCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/InventoryCountCreate} obj Optional instance to populate.
     * @return {module:model/InventoryCountCreate} The populated <code>InventoryCountCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InventoryCountCreate();

            if (data.hasOwnProperty('countDate')) {
                obj['countDate'] = ApiClient.convertToType(data['countDate'], 'Date');
            }
            if (data.hasOwnProperty('countNumber')) {
                obj['countNumber'] = ApiClient.convertToType(data['countNumber'], 'String');
            }
            if (data.hasOwnProperty('lineItems')) {
                obj['lineItems'] = ApiClient.convertToType(data['lineItems'], Object);
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], InventoryCountStatus);
            }
            if (data.hasOwnProperty('warehouseId')) {
                obj['warehouseId'] = ApiClient.convertToType(data['warehouseId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>InventoryCountCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>InventoryCountCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of InventoryCountCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['countNumber'] && !(typeof data['countNumber'] === 'string' || data['countNumber'] instanceof String)) {
            throw new Error("Expected the field `countNumber` to be a primitive type in the JSON string but got " + data['countNumber']);
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }
        // ensure the json data is a string
        if (data['warehouseId'] && !(typeof data['warehouseId'] === 'string' || data['warehouseId'] instanceof String)) {
            throw new Error("Expected the field `warehouseId` to be a primitive type in the JSON string but got " + data['warehouseId']);
        }

        return true;
    }


}

InventoryCountCreate.RequiredProperties = ["countDate", "countNumber", "lineItems", "status", "warehouseId"];

/**
 * @member {Date} countDate
 */
InventoryCountCreate.prototype['countDate'] = undefined;

/**
 * @member {String} countNumber
 */
InventoryCountCreate.prototype['countNumber'] = undefined;

/**
 * JSON array of `{product_id, name, sku, expected_quantity, counted_quantity, bin_location?, batch_number?, variance}`.
 * @member {Object} lineItems
 */
InventoryCountCreate.prototype['lineItems'] = undefined;

/**
 * @member {String} notes
 */
InventoryCountCreate.prototype['notes'] = undefined;

/**
 * One of: draft | counting | reviewed | posted
 * @member {module:model/InventoryCountStatus} status
 */
InventoryCountCreate.prototype['status'] = undefined;

/**
 * References the warehouse entity.
 * @member {String} warehouseId
 */
InventoryCountCreate.prototype['warehouseId'] = undefined;






export default InventoryCountCreate;

