/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmploymentType from './EmploymentType';
import JobPostingStatus from './JobPostingStatus';

/**
 * The JobPostingCreate model module.
 * @module model/JobPostingCreate
 * @version 0.1.0
 */
class JobPostingCreate {
    /**
     * Constructs a new <code>JobPostingCreate</code>.
     * @alias module:model/JobPostingCreate
     * @param description {String} What the job is; markdown/HTML.
     * @param remote {Boolean} 
     * @param requiredSkills {Object} List of required skill names (JSON array of strings).
     * @param status {module:model/JobPostingStatus} draft | published | closed
     * @param title {String} 
     */
    constructor(description, remote, requiredSkills, status, title) { 
        
        JobPostingCreate.initialize(this, description, remote, requiredSkills, status, title);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, description, remote, requiredSkills, status, title) { 
        obj['description'] = description;
        obj['remote'] = remote;
        obj['requiredSkills'] = requiredSkills;
        obj['status'] = status;
        obj['title'] = title;
    }

    /**
     * Constructs a <code>JobPostingCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/JobPostingCreate} obj Optional instance to populate.
     * @return {module:model/JobPostingCreate} The populated <code>JobPostingCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new JobPostingCreate();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
            if (data.hasOwnProperty('department')) {
                obj['department'] = ApiClient.convertToType(data['department'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('employmentType')) {
                obj['employmentType'] = ApiClient.convertToType(data['employmentType'], EmploymentType);
            }
            if (data.hasOwnProperty('location')) {
                obj['location'] = ApiClient.convertToType(data['location'], 'String');
            }
            if (data.hasOwnProperty('remote')) {
                obj['remote'] = ApiClient.convertToType(data['remote'], 'Boolean');
            }
            if (data.hasOwnProperty('requiredSkills')) {
                obj['requiredSkills'] = ApiClient.convertToType(data['requiredSkills'], Object);
            }
            if (data.hasOwnProperty('requirements')) {
                obj['requirements'] = ApiClient.convertToType(data['requirements'], 'String');
            }
            if (data.hasOwnProperty('salaryMax')) {
                obj['salaryMax'] = ApiClient.convertToType(data['salaryMax'], 'Number');
            }
            if (data.hasOwnProperty('salaryMin')) {
                obj['salaryMin'] = ApiClient.convertToType(data['salaryMin'], 'Number');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], JobPostingStatus);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>JobPostingCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>JobPostingCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of JobPostingCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }
        // ensure the json data is a string
        if (data['department'] && !(typeof data['department'] === 'string' || data['department'] instanceof String)) {
            throw new Error("Expected the field `department` to be a primitive type in the JSON string but got " + data['department']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['location'] && !(typeof data['location'] === 'string' || data['location'] instanceof String)) {
            throw new Error("Expected the field `location` to be a primitive type in the JSON string but got " + data['location']);
        }
        // ensure the json data is a string
        if (data['requirements'] && !(typeof data['requirements'] === 'string' || data['requirements'] instanceof String)) {
            throw new Error("Expected the field `requirements` to be a primitive type in the JSON string but got " + data['requirements']);
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }

        return true;
    }


}

JobPostingCreate.RequiredProperties = ["description", "remote", "requiredSkills", "status", "title"];

/**
 * @member {String} currency
 */
JobPostingCreate.prototype['currency'] = undefined;

/**
 * @member {String} department
 */
JobPostingCreate.prototype['department'] = undefined;

/**
 * What the job is; markdown/HTML.
 * @member {String} description
 */
JobPostingCreate.prototype['description'] = undefined;

/**
 * full_time | part_time | contract | internship | temporary
 * @member {module:model/EmploymentType} employmentType
 */
JobPostingCreate.prototype['employmentType'] = undefined;

/**
 * @member {String} location
 */
JobPostingCreate.prototype['location'] = undefined;

/**
 * @member {Boolean} remote
 */
JobPostingCreate.prototype['remote'] = undefined;

/**
 * List of required skill names (JSON array of strings).
 * @member {Object} requiredSkills
 */
JobPostingCreate.prototype['requiredSkills'] = undefined;

/**
 * Structured profile of the required candidate (skills, experience).
 * @member {String} requirements
 */
JobPostingCreate.prototype['requirements'] = undefined;

/**
 * @member {Number} salaryMax
 */
JobPostingCreate.prototype['salaryMax'] = undefined;

/**
 * @member {Number} salaryMin
 */
JobPostingCreate.prototype['salaryMin'] = undefined;

/**
 * draft | published | closed
 * @member {module:model/JobPostingStatus} status
 */
JobPostingCreate.prototype['status'] = undefined;

/**
 * @member {String} title
 */
JobPostingCreate.prototype['title'] = undefined;






export default JobPostingCreate;

