/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KonzernBeteiligung model module.
 * @module model/KonzernBeteiligung
 * @version 0.1.0
 */
class KonzernBeteiligung {
    /**
     * Constructs a new <code>KonzernBeteiligung</code>.
     * @alias module:model/KonzernBeteiligung
     * @param companyName {String} 
     * @param controlBasis {Array.<String>} Erfüllte Kontroll-Indikatoren (§ 290 Abs. 2 HGB) als deutsche Bezeichnungen.
     * @param controlled {Boolean} 
     * @param ownershipPct {String} 
     */
    constructor(companyName, controlBasis, controlled, ownershipPct) { 
        
        KonzernBeteiligung.initialize(this, companyName, controlBasis, controlled, ownershipPct);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, companyName, controlBasis, controlled, ownershipPct) { 
        obj['company_name'] = companyName;
        obj['control_basis'] = controlBasis;
        obj['controlled'] = controlled;
        obj['ownership_pct'] = ownershipPct;
    }

    /**
     * Constructs a <code>KonzernBeteiligung</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KonzernBeteiligung} obj Optional instance to populate.
     * @return {module:model/KonzernBeteiligung} The populated <code>KonzernBeteiligung</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KonzernBeteiligung();

            if (data.hasOwnProperty('company_name')) {
                obj['company_name'] = ApiClient.convertToType(data['company_name'], 'String');
            }
            if (data.hasOwnProperty('control_basis')) {
                obj['control_basis'] = ApiClient.convertToType(data['control_basis'], ['String']);
            }
            if (data.hasOwnProperty('controlled')) {
                obj['controlled'] = ApiClient.convertToType(data['controlled'], 'Boolean');
            }
            if (data.hasOwnProperty('ownership_pct')) {
                obj['ownership_pct'] = ApiClient.convertToType(data['ownership_pct'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>KonzernBeteiligung</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>KonzernBeteiligung</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of KonzernBeteiligung.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['company_name'] && !(typeof data['company_name'] === 'string' || data['company_name'] instanceof String)) {
            throw new Error("Expected the field `company_name` to be a primitive type in the JSON string but got " + data['company_name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['control_basis'])) {
            throw new Error("Expected the field `control_basis` to be an array in the JSON data but got " + data['control_basis']);
        }
        // ensure the json data is a string
        if (data['ownership_pct'] && !(typeof data['ownership_pct'] === 'string' || data['ownership_pct'] instanceof String)) {
            throw new Error("Expected the field `ownership_pct` to be a primitive type in the JSON string but got " + data['ownership_pct']);
        }

        return true;
    }


}

KonzernBeteiligung.RequiredProperties = ["company_name", "control_basis", "controlled", "ownership_pct"];

/**
 * @member {String} company_name
 */
KonzernBeteiligung.prototype['company_name'] = undefined;

/**
 * Erfüllte Kontroll-Indikatoren (§ 290 Abs. 2 HGB) als deutsche Bezeichnungen.
 * @member {Array.<String>} control_basis
 */
KonzernBeteiligung.prototype['control_basis'] = undefined;

/**
 * @member {Boolean} controlled
 */
KonzernBeteiligung.prototype['controlled'] = undefined;

/**
 * @member {String} ownership_pct
 */
KonzernBeteiligung.prototype['ownership_pct'] = undefined;






export default KonzernBeteiligung;

