/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class LanguageCode.
* @enum {}
* @readonly
*/
export default class LanguageCode {
    
        /**
         * value: "DE"
         * @const
         */
        "DE" = "DE";

    
        /**
         * value: "EN"
         * @const
         */
        "EN" = "EN";

    
        /**
         * value: "FR"
         * @const
         */
        "FR" = "FR";

    
        /**
         * value: "ES"
         * @const
         */
        "ES" = "ES";

    
        /**
         * value: "IT"
         * @const
         */
        "IT" = "IT";

    
        /**
         * value: "NL"
         * @const
         */
        "NL" = "NL";

    
        /**
         * value: "PL"
         * @const
         */
        "PL" = "PL";

    
        /**
         * value: "PT"
         * @const
         */
        "PT" = "PT";

    
        /**
         * value: "TR"
         * @const
         */
        "TR" = "TR";

    
        /**
         * value: "RU"
         * @const
         */
        "RU" = "RU";

    
        /**
         * value: "UK"
         * @const
         */
        "UK" = "UK";

    
        /**
         * value: "CS"
         * @const
         */
        "CS" = "CS";

    
        /**
         * value: "EL"
         * @const
         */
        "EL" = "EL";

    
        /**
         * value: "HU"
         * @const
         */
        "HU" = "HU";

    
        /**
         * value: "RO"
         * @const
         */
        "RO" = "RO";

    
        /**
         * value: "SV"
         * @const
         */
        "SV" = "SV";

    
        /**
         * value: "DA"
         * @const
         */
        "DA" = "DA";

    
        /**
         * value: "FI"
         * @const
         */
        "FI" = "FI";

    
        /**
         * value: "NO"
         * @const
         */
        "NO" = "NO";

    
        /**
         * value: "SK"
         * @const
         */
        "SK" = "SK";

    
        /**
         * value: "SL"
         * @const
         */
        "SL" = "SL";

    
        /**
         * value: "HR"
         * @const
         */
        "HR" = "HR";

    
        /**
         * value: "BG"
         * @const
         */
        "BG" = "BG";

    
        /**
         * value: "ET"
         * @const
         */
        "ET" = "ET";

    
        /**
         * value: "LV"
         * @const
         */
        "LV" = "LV";

    
        /**
         * value: "LT"
         * @const
         */
        "LT" = "LT";

    
        /**
         * value: "MT"
         * @const
         */
        "MT" = "MT";

    
        /**
         * value: "AR"
         * @const
         */
        "AR" = "AR";

    
        /**
         * value: "ZH"
         * @const
         */
        "ZH" = "ZH";

    
        /**
         * value: "JA"
         * @const
         */
        "JA" = "JA";

    
        /**
         * value: "KO"
         * @const
         */
        "KO" = "KO";

    
        /**
         * value: "TH"
         * @const
         */
        "TH" = "TH";

    
        /**
         * value: "VI"
         * @const
         */
        "VI" = "VI";

    
        /**
         * value: "ID"
         * @const
         */
        "ID" = "ID";

    
        /**
         * value: "HI"
         * @const
         */
        "HI" = "HI";

    
        /**
         * value: "AB"
         * @const
         */
        "AB" = "AB";

    
        /**
         * value: "AA"
         * @const
         */
        "AA" = "AA";

    
        /**
         * value: "AF"
         * @const
         */
        "AF" = "AF";

    
        /**
         * value: "AK"
         * @const
         */
        "AK" = "AK";

    
        /**
         * value: "SQ"
         * @const
         */
        "SQ" = "SQ";

    
        /**
         * value: "AM"
         * @const
         */
        "AM" = "AM";

    
        /**
         * value: "AN"
         * @const
         */
        "AN" = "AN";

    
        /**
         * value: "HY"
         * @const
         */
        "HY" = "HY";

    
        /**
         * value: "AS"
         * @const
         */
        "AS" = "AS";

    
        /**
         * value: "AV"
         * @const
         */
        "AV" = "AV";

    
        /**
         * value: "AE"
         * @const
         */
        "AE" = "AE";

    
        /**
         * value: "AY"
         * @const
         */
        "AY" = "AY";

    
        /**
         * value: "AZ"
         * @const
         */
        "AZ" = "AZ";

    
        /**
         * value: "BM"
         * @const
         */
        "BM" = "BM";

    
        /**
         * value: "BA"
         * @const
         */
        "BA" = "BA";

    
        /**
         * value: "EU"
         * @const
         */
        "EU" = "EU";

    
        /**
         * value: "BE"
         * @const
         */
        "BE" = "BE";

    
        /**
         * value: "BN"
         * @const
         */
        "BN" = "BN";

    
        /**
         * value: "BI"
         * @const
         */
        "BI" = "BI";

    
        /**
         * value: "BS"
         * @const
         */
        "BS" = "BS";

    
        /**
         * value: "BR"
         * @const
         */
        "BR" = "BR";

    
        /**
         * value: "MY"
         * @const
         */
        "MY" = "MY";

    
        /**
         * value: "CA"
         * @const
         */
        "CA" = "CA";

    
        /**
         * value: "CH"
         * @const
         */
        "CH" = "CH";

    
        /**
         * value: "CE"
         * @const
         */
        "CE" = "CE";

    
        /**
         * value: "NY"
         * @const
         */
        "NY" = "NY";

    
        /**
         * value: "CU"
         * @const
         */
        "CU" = "CU";

    
        /**
         * value: "CV"
         * @const
         */
        "CV" = "CV";

    
        /**
         * value: "KW"
         * @const
         */
        "KW" = "KW";

    
        /**
         * value: "CO"
         * @const
         */
        "CO" = "CO";

    
        /**
         * value: "CR"
         * @const
         */
        "CR" = "CR";

    
        /**
         * value: "DV"
         * @const
         */
        "DV" = "DV";

    
        /**
         * value: "DZ"
         * @const
         */
        "DZ" = "DZ";

    
        /**
         * value: "EO"
         * @const
         */
        "EO" = "EO";

    
        /**
         * value: "EE"
         * @const
         */
        "EE" = "EE";

    
        /**
         * value: "FO"
         * @const
         */
        "FO" = "FO";

    
        /**
         * value: "FJ"
         * @const
         */
        "FJ" = "FJ";

    
        /**
         * value: "FY"
         * @const
         */
        "FY" = "FY";

    
        /**
         * value: "FF"
         * @const
         */
        "FF" = "FF";

    
        /**
         * value: "GD"
         * @const
         */
        "GD" = "GD";

    
        /**
         * value: "GL"
         * @const
         */
        "GL" = "GL";

    
        /**
         * value: "LG"
         * @const
         */
        "LG" = "LG";

    
        /**
         * value: "KA"
         * @const
         */
        "KA" = "KA";

    
        /**
         * value: "KL"
         * @const
         */
        "KL" = "KL";

    
        /**
         * value: "GN"
         * @const
         */
        "GN" = "GN";

    
        /**
         * value: "GU"
         * @const
         */
        "GU" = "GU";

    
        /**
         * value: "HT"
         * @const
         */
        "HT" = "HT";

    
        /**
         * value: "HA"
         * @const
         */
        "HA" = "HA";

    
        /**
         * value: "HE"
         * @const
         */
        "HE" = "HE";

    
        /**
         * value: "HZ"
         * @const
         */
        "HZ" = "HZ";

    
        /**
         * value: "HO"
         * @const
         */
        "HO" = "HO";

    
        /**
         * value: "IS"
         * @const
         */
        "IS" = "IS";

    
        /**
         * value: "IO"
         * @const
         */
        "IO" = "IO";

    
        /**
         * value: "IG"
         * @const
         */
        "IG" = "IG";

    
        /**
         * value: "IA"
         * @const
         */
        "IA" = "IA";

    
        /**
         * value: "IE"
         * @const
         */
        "IE" = "IE";

    
        /**
         * value: "IU"
         * @const
         */
        "IU" = "IU";

    
        /**
         * value: "IK"
         * @const
         */
        "IK" = "IK";

    
        /**
         * value: "GA"
         * @const
         */
        "GA" = "GA";

    
        /**
         * value: "JV"
         * @const
         */
        "JV" = "JV";

    
        /**
         * value: "KN"
         * @const
         */
        "KN" = "KN";

    
        /**
         * value: "KR"
         * @const
         */
        "KR" = "KR";

    
        /**
         * value: "KS"
         * @const
         */
        "KS" = "KS";

    
        /**
         * value: "KK"
         * @const
         */
        "KK" = "KK";

    
        /**
         * value: "KM"
         * @const
         */
        "KM" = "KM";

    
        /**
         * value: "KI"
         * @const
         */
        "KI" = "KI";

    
        /**
         * value: "RW"
         * @const
         */
        "RW" = "RW";

    
        /**
         * value: "KY"
         * @const
         */
        "KY" = "KY";

    
        /**
         * value: "KV"
         * @const
         */
        "KV" = "KV";

    
        /**
         * value: "KG"
         * @const
         */
        "KG" = "KG";

    
        /**
         * value: "KJ"
         * @const
         */
        "KJ" = "KJ";

    
        /**
         * value: "KU"
         * @const
         */
        "KU" = "KU";

    
        /**
         * value: "LO"
         * @const
         */
        "LO" = "LO";

    
        /**
         * value: "LA"
         * @const
         */
        "LA" = "LA";

    
        /**
         * value: "LI"
         * @const
         */
        "LI" = "LI";

    
        /**
         * value: "LN"
         * @const
         */
        "LN" = "LN";

    
        /**
         * value: "LU"
         * @const
         */
        "LU" = "LU";

    
        /**
         * value: "LB"
         * @const
         */
        "LB" = "LB";

    
        /**
         * value: "MK"
         * @const
         */
        "MK" = "MK";

    
        /**
         * value: "MG"
         * @const
         */
        "MG" = "MG";

    
        /**
         * value: "MS"
         * @const
         */
        "MS" = "MS";

    
        /**
         * value: "ML"
         * @const
         */
        "ML" = "ML";

    
        /**
         * value: "GV"
         * @const
         */
        "GV" = "GV";

    
        /**
         * value: "MI"
         * @const
         */
        "MI" = "MI";

    
        /**
         * value: "MR"
         * @const
         */
        "MR" = "MR";

    
        /**
         * value: "MH"
         * @const
         */
        "MH" = "MH";

    
        /**
         * value: "MN"
         * @const
         */
        "MN" = "MN";

    
        /**
         * value: "NA"
         * @const
         */
        "NA" = "NA";

    
        /**
         * value: "NV"
         * @const
         */
        "NV" = "NV";

    
        /**
         * value: "ND"
         * @const
         */
        "ND" = "ND";

    
        /**
         * value: "NR"
         * @const
         */
        "NR" = "NR";

    
        /**
         * value: "NG"
         * @const
         */
        "NG" = "NG";

    
        /**
         * value: "NE"
         * @const
         */
        "NE" = "NE";

    
        /**
         * value: "NB"
         * @const
         */
        "NB" = "NB";

    
        /**
         * value: "NN"
         * @const
         */
        "NN" = "NN";

    
        /**
         * value: "OC"
         * @const
         */
        "OC" = "OC";

    
        /**
         * value: "OJ"
         * @const
         */
        "OJ" = "OJ";

    
        /**
         * value: "OR"
         * @const
         */
        "OR" = "OR";

    
        /**
         * value: "OM"
         * @const
         */
        "OM" = "OM";

    
        /**
         * value: "OS"
         * @const
         */
        "OS" = "OS";

    
        /**
         * value: "PI"
         * @const
         */
        "PI" = "PI";

    
        /**
         * value: "PS"
         * @const
         */
        "PS" = "PS";

    
        /**
         * value: "FA"
         * @const
         */
        "FA" = "FA";

    
        /**
         * value: "PA"
         * @const
         */
        "PA" = "PA";

    
        /**
         * value: "QU"
         * @const
         */
        "QU" = "QU";

    
        /**
         * value: "RM"
         * @const
         */
        "RM" = "RM";

    
        /**
         * value: "RN"
         * @const
         */
        "RN" = "RN";

    
        /**
         * value: "SE"
         * @const
         */
        "SE" = "SE";

    
        /**
         * value: "SM"
         * @const
         */
        "SM" = "SM";

    
        /**
         * value: "SG"
         * @const
         */
        "SG" = "SG";

    
        /**
         * value: "SA"
         * @const
         */
        "SA" = "SA";

    
        /**
         * value: "SC"
         * @const
         */
        "SC" = "SC";

    
        /**
         * value: "SR"
         * @const
         */
        "SR" = "SR";

    
        /**
         * value: "SN"
         * @const
         */
        "SN" = "SN";

    
        /**
         * value: "SD"
         * @const
         */
        "SD" = "SD";

    
        /**
         * value: "SI"
         * @const
         */
        "SI" = "SI";

    
        /**
         * value: "SO"
         * @const
         */
        "SO" = "SO";

    
        /**
         * value: "ST"
         * @const
         */
        "ST" = "ST";

    
        /**
         * value: "SU"
         * @const
         */
        "SU" = "SU";

    
        /**
         * value: "SW"
         * @const
         */
        "SW" = "SW";

    
        /**
         * value: "SS"
         * @const
         */
        "SS" = "SS";

    
        /**
         * value: "TL"
         * @const
         */
        "TL" = "TL";

    
        /**
         * value: "TY"
         * @const
         */
        "TY" = "TY";

    
        /**
         * value: "TG"
         * @const
         */
        "TG" = "TG";

    
        /**
         * value: "TA"
         * @const
         */
        "TA" = "TA";

    
        /**
         * value: "TT"
         * @const
         */
        "TT" = "TT";

    
        /**
         * value: "TE"
         * @const
         */
        "TE" = "TE";

    
        /**
         * value: "BO"
         * @const
         */
        "BO" = "BO";

    
        /**
         * value: "TI"
         * @const
         */
        "TI" = "TI";

    
        /**
         * value: "TO"
         * @const
         */
        "TO" = "TO";

    
        /**
         * value: "TS"
         * @const
         */
        "TS" = "TS";

    
        /**
         * value: "TN"
         * @const
         */
        "TN" = "TN";

    
        /**
         * value: "TK"
         * @const
         */
        "TK" = "TK";

    
        /**
         * value: "TW"
         * @const
         */
        "TW" = "TW";

    
        /**
         * value: "UG"
         * @const
         */
        "UG" = "UG";

    
        /**
         * value: "UR"
         * @const
         */
        "UR" = "UR";

    
        /**
         * value: "UZ"
         * @const
         */
        "UZ" = "UZ";

    
        /**
         * value: "VE"
         * @const
         */
        "VE" = "VE";

    
        /**
         * value: "VO"
         * @const
         */
        "VO" = "VO";

    
        /**
         * value: "WA"
         * @const
         */
        "WA" = "WA";

    
        /**
         * value: "CY"
         * @const
         */
        "CY" = "CY";

    
        /**
         * value: "WO"
         * @const
         */
        "WO" = "WO";

    
        /**
         * value: "XH"
         * @const
         */
        "XH" = "XH";

    
        /**
         * value: "II"
         * @const
         */
        "II" = "II";

    
        /**
         * value: "YI"
         * @const
         */
        "YI" = "YI";

    
        /**
         * value: "YO"
         * @const
         */
        "YO" = "YO";

    
        /**
         * value: "ZA"
         * @const
         */
        "ZA" = "ZA";

    
        /**
         * value: "ZU"
         * @const
         */
        "ZU" = "ZU";

    
        /**
         * value: "BB"
         * @const
         */
        "BB" = "BB";

    
        /**
         * value: "CB"
         * @const
         */
        "CB" = "CB";

    
        /**
         * value: "DB"
         * @const
         */
        "DB" = "DB";

    
        /**
         * value: "EB"
         * @const
         */
        "EB" = "EB";

    
        /**
         * value: "FB"
         * @const
         */
        "FB" = "FB";

    
        /**
         * value: "GB"
         * @const
         */
        "GB" = "GB";

    
        /**
         * value: "HB"
         * @const
         */
        "HB" = "HB";

    
        /**
         * value: "IB"
         * @const
         */
        "IB" = "IB";

    
        /**
         * value: "JB"
         * @const
         */
        "JB" = "JB";

    
        /**
         * value: "KB"
         * @const
         */
        "KB" = "KB";

    
        /**
         * value: "MB"
         * @const
         */
        "MB" = "MB";

    
        /**
         * value: "OB"
         * @const
         */
        "OB" = "OB";

    
        /**
         * value: "PB"
         * @const
         */
        "PB" = "PB";

    
        /**
         * value: "QB"
         * @const
         */
        "QB" = "QB";

    
        /**
         * value: "RB"
         * @const
         */
        "RB" = "RB";

    
        /**
         * value: "SB"
         * @const
         */
        "SB" = "SB";

    
        /**
         * value: "TB"
         * @const
         */
        "TB" = "TB";

    
        /**
         * value: "UB"
         * @const
         */
        "UB" = "UB";

    
        /**
         * value: "VB"
         * @const
         */
        "VB" = "VB";

    
        /**
         * value: "WB"
         * @const
         */
        "WB" = "WB";

    
        /**
         * value: "XB"
         * @const
         */
        "XB" = "XB";

    
        /**
         * value: "YB"
         * @const
         */
        "YB" = "YB";

    
        /**
         * value: "ZB"
         * @const
         */
        "ZB" = "ZB";

    

    /**
    * Returns a <code>LanguageCode</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/LanguageCode} The enum <code>LanguageCode</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

