/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import SyncLogStatus from './SyncLogStatus';
import SyncType from './SyncType';

/**
 * The MarketplaceSyncLog model module.
 * @module model/MarketplaceSyncLog
 * @version 0.1.0
 */
class MarketplaceSyncLog {
    /**
     * Constructs a new <code>MarketplaceSyncLog</code>.
     * @alias module:model/MarketplaceSyncLog
     * @param connectionId {String} References the marketplace connection entity.
     * @param itemsFailed {Number} 
     * @param itemsSynced {Number} 
     * @param platform {String} 
     * @param startedAt {Date} 
     * @param status {module:model/SyncLogStatus} 
     * @param syncType {module:model/SyncType} 
     */
    constructor(connectionId, itemsFailed, itemsSynced, platform, startedAt, status, syncType) { 
        
        MarketplaceSyncLog.initialize(this, connectionId, itemsFailed, itemsSynced, platform, startedAt, status, syncType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, connectionId, itemsFailed, itemsSynced, platform, startedAt, status, syncType) { 
        obj['connectionId'] = connectionId;
        obj['itemsFailed'] = itemsFailed;
        obj['itemsSynced'] = itemsSynced;
        obj['platform'] = platform;
        obj['startedAt'] = startedAt;
        obj['status'] = status;
        obj['syncType'] = syncType;
    }

    /**
     * Constructs a <code>MarketplaceSyncLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MarketplaceSyncLog} obj Optional instance to populate.
     * @return {module:model/MarketplaceSyncLog} The populated <code>MarketplaceSyncLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MarketplaceSyncLog();

            if (data.hasOwnProperty('completedAt')) {
                obj['completedAt'] = ApiClient.convertToType(data['completedAt'], 'Date');
            }
            if (data.hasOwnProperty('connectionId')) {
                obj['connectionId'] = ApiClient.convertToType(data['connectionId'], 'String');
            }
            if (data.hasOwnProperty('errorMessage')) {
                obj['errorMessage'] = ApiClient.convertToType(data['errorMessage'], 'String');
            }
            if (data.hasOwnProperty('itemsFailed')) {
                obj['itemsFailed'] = ApiClient.convertToType(data['itemsFailed'], 'Number');
            }
            if (data.hasOwnProperty('itemsSynced')) {
                obj['itemsSynced'] = ApiClient.convertToType(data['itemsSynced'], 'Number');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
            }
            if (data.hasOwnProperty('startedAt')) {
                obj['startedAt'] = ApiClient.convertToType(data['startedAt'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = SyncLogStatus.constructFromObject(data['status']);
            }
            if (data.hasOwnProperty('syncType')) {
                obj['syncType'] = SyncType.constructFromObject(data['syncType']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MarketplaceSyncLog</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MarketplaceSyncLog</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MarketplaceSyncLog.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['connectionId'] && !(typeof data['connectionId'] === 'string' || data['connectionId'] instanceof String)) {
            throw new Error("Expected the field `connectionId` to be a primitive type in the JSON string but got " + data['connectionId']);
        }
        // ensure the json data is a string
        if (data['errorMessage'] && !(typeof data['errorMessage'] === 'string' || data['errorMessage'] instanceof String)) {
            throw new Error("Expected the field `errorMessage` to be a primitive type in the JSON string but got " + data['errorMessage']);
        }
        // ensure the json data is a string
        if (data['platform'] && !(typeof data['platform'] === 'string' || data['platform'] instanceof String)) {
            throw new Error("Expected the field `platform` to be a primitive type in the JSON string but got " + data['platform']);
        }

        return true;
    }


}

MarketplaceSyncLog.RequiredProperties = ["connectionId", "itemsFailed", "itemsSynced", "platform", "startedAt", "status", "syncType"];

/**
 * @member {Date} completedAt
 */
MarketplaceSyncLog.prototype['completedAt'] = undefined;

/**
 * References the marketplace connection entity.
 * @member {String} connectionId
 */
MarketplaceSyncLog.prototype['connectionId'] = undefined;

/**
 * @member {String} errorMessage
 */
MarketplaceSyncLog.prototype['errorMessage'] = undefined;

/**
 * @member {Number} itemsFailed
 */
MarketplaceSyncLog.prototype['itemsFailed'] = undefined;

/**
 * @member {Number} itemsSynced
 */
MarketplaceSyncLog.prototype['itemsSynced'] = undefined;

/**
 * @member {String} platform
 */
MarketplaceSyncLog.prototype['platform'] = undefined;

/**
 * @member {Date} startedAt
 */
MarketplaceSyncLog.prototype['startedAt'] = undefined;

/**
 * @member {module:model/SyncLogStatus} status
 */
MarketplaceSyncLog.prototype['status'] = undefined;

/**
 * @member {module:model/SyncType} syncType
 */
MarketplaceSyncLog.prototype['syncType'] = undefined;






export default MarketplaceSyncLog;

