/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ShippingRate from './ShippingRate';

/**
 * The MethodSuitability model module.
 * @module model/MethodSuitability
 * @version 0.1.0
 */
class MethodSuitability {
    /**
     * Constructs a new <code>MethodSuitability</code>.
     * @alias module:model/MethodSuitability
     * @param carrier {String} 
     * @param reasons {Array.<String>} 
     * @param service {String} 
     * @param suitable {Boolean} 
     */
    constructor(carrier, reasons, service, suitable) { 
        
        MethodSuitability.initialize(this, carrier, reasons, service, suitable);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, carrier, reasons, service, suitable) { 
        obj['carrier'] = carrier;
        obj['reasons'] = reasons;
        obj['service'] = service;
        obj['suitable'] = suitable;
    }

    /**
     * Constructs a <code>MethodSuitability</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MethodSuitability} obj Optional instance to populate.
     * @return {module:model/MethodSuitability} The populated <code>MethodSuitability</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MethodSuitability();

            if (data.hasOwnProperty('carrier')) {
                obj['carrier'] = ApiClient.convertToType(data['carrier'], 'String');
            }
            if (data.hasOwnProperty('rate')) {
                obj['rate'] = ApiClient.convertToType(data['rate'], ShippingRate);
            }
            if (data.hasOwnProperty('reasons')) {
                obj['reasons'] = ApiClient.convertToType(data['reasons'], ['String']);
            }
            if (data.hasOwnProperty('service')) {
                obj['service'] = ApiClient.convertToType(data['service'], 'String');
            }
            if (data.hasOwnProperty('suitable')) {
                obj['suitable'] = ApiClient.convertToType(data['suitable'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>MethodSuitability</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>MethodSuitability</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of MethodSuitability.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['carrier'] && !(typeof data['carrier'] === 'string' || data['carrier'] instanceof String)) {
            throw new Error("Expected the field `carrier` to be a primitive type in the JSON string but got " + data['carrier']);
        }
        // validate the optional field `rate`
        if (data['rate']) { // data not null
          ShippingRate.validateJSON(data['rate']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['reasons'])) {
            throw new Error("Expected the field `reasons` to be an array in the JSON data but got " + data['reasons']);
        }
        // ensure the json data is a string
        if (data['service'] && !(typeof data['service'] === 'string' || data['service'] instanceof String)) {
            throw new Error("Expected the field `service` to be a primitive type in the JSON string but got " + data['service']);
        }

        return true;
    }


}

MethodSuitability.RequiredProperties = ["carrier", "reasons", "service", "suitable"];

/**
 * @member {String} carrier
 */
MethodSuitability.prototype['carrier'] = undefined;

/**
 * @member {module:model/ShippingRate} rate
 */
MethodSuitability.prototype['rate'] = undefined;

/**
 * @member {Array.<String>} reasons
 */
MethodSuitability.prototype['reasons'] = undefined;

/**
 * @member {String} service
 */
MethodSuitability.prototype['service'] = undefined;

/**
 * @member {Boolean} suitable
 */
MethodSuitability.prototype['suitable'] = undefined;






export default MethodSuitability;

