/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MovementType.
* @enum {}
* @readonly
*/
export default class MovementType {
    
        /**
         * value: "goods_receipt"
         * @const
         */
        "goods_receipt" = "goods_receipt";

    
        /**
         * value: "goods_receipt_reversal"
         * @const
         */
        "goods_receipt_reversal" = "goods_receipt_reversal";

    
        /**
         * value: "transfer_in"
         * @const
         */
        "transfer_in" = "transfer_in";

    
        /**
         * value: "transfer_out"
         * @const
         */
        "transfer_out" = "transfer_out";

    
        /**
         * value: "return_restock"
         * @const
         */
        "return_restock" = "return_restock";

    
        /**
         * value: "production_consumption"
         * @const
         */
        "production_consumption" = "production_consumption";

    
        /**
         * value: "production_completion"
         * @const
         */
        "production_completion" = "production_completion";

    
        /**
         * value: "inventory_adjustment"
         * @const
         */
        "inventory_adjustment" = "inventory_adjustment";

    
        /**
         * value: "sale"
         * @const
         */
        "sale" = "sale";

    
        /**
         * value: "other"
         * @const
         */
        "other" = "other";

    

    /**
    * Returns a <code>MovementType</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MovementType} The enum <code>MovementType</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

