/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PayrollPayPayload model module.
 * @module model/PayrollPayPayload
 * @version 0.1.0
 */
class PayrollPayPayload {
    /**
     * Constructs a new <code>PayrollPayPayload</code>.
     * @alias module:model/PayrollPayPayload
     * @param paymentDate {Date} 
     */
    constructor(paymentDate) { 
        
        PayrollPayPayload.initialize(this, paymentDate);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, paymentDate) { 
        obj['payment_date'] = paymentDate;
    }

    /**
     * Constructs a <code>PayrollPayPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PayrollPayPayload} obj Optional instance to populate.
     * @return {module:model/PayrollPayPayload} The populated <code>PayrollPayPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PayrollPayPayload();

            if (data.hasOwnProperty('payment_date')) {
                obj['payment_date'] = ApiClient.convertToType(data['payment_date'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PayrollPayPayload</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PayrollPayPayload</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PayrollPayPayload.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PayrollPayPayload.RequiredProperties = ["payment_date"];

/**
 * @member {Date} payment_date
 */
PayrollPayPayload.prototype['payment_date'] = undefined;






export default PayrollPayPayload;

