/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import PluginErrorOneOf from './PluginErrorOneOf';
import PluginErrorOneOf1 from './PluginErrorOneOf1';
import PluginErrorOneOf2 from './PluginErrorOneOf2';
import PluginErrorOneOf3 from './PluginErrorOneOf3';
import PluginErrorOneOf4 from './PluginErrorOneOf4';
import PluginErrorOneOf5 from './PluginErrorOneOf5';
import PluginErrorOneOf6 from './PluginErrorOneOf6';

/**
 * The PluginError model module.
 * @module model/PluginError
 * @version 0.1.0
 */
class PluginError {
    /**
     * Constructs a new <code>PluginError</code>.
     * @alias module:model/PluginError
     * @param {(module:model/PluginErrorOneOf|module:model/PluginErrorOneOf1|module:model/PluginErrorOneOf2|module:model/PluginErrorOneOf3|module:model/PluginErrorOneOf4|module:model/PluginErrorOneOf5|module:model/PluginErrorOneOf6)} instance The actual instance to initialize PluginError.
     */
    constructor(instance = null) {
        if (instance === null) {
            this.actualInstance = null;
            return;
        }
        var match = 0;
        var errorMessages = [];
        try {
            if (instance instanceof PluginErrorOneOf) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf from JS object
                this.actualInstance = PluginErrorOneOf.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf
            errorMessages.push("Failed to construct PluginErrorOneOf: " + err)
        }

        try {
            if (instance instanceof PluginErrorOneOf1) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf1.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf1 from JS object
                this.actualInstance = PluginErrorOneOf1.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf1
            errorMessages.push("Failed to construct PluginErrorOneOf1: " + err)
        }

        try {
            if (instance instanceof PluginErrorOneOf2) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf2.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf2 from JS object
                this.actualInstance = PluginErrorOneOf2.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf2
            errorMessages.push("Failed to construct PluginErrorOneOf2: " + err)
        }

        try {
            if (instance instanceof PluginErrorOneOf3) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf3.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf3 from JS object
                this.actualInstance = PluginErrorOneOf3.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf3
            errorMessages.push("Failed to construct PluginErrorOneOf3: " + err)
        }

        try {
            if (instance instanceof PluginErrorOneOf4) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf4.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf4 from JS object
                this.actualInstance = PluginErrorOneOf4.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf4
            errorMessages.push("Failed to construct PluginErrorOneOf4: " + err)
        }

        try {
            if (instance instanceof PluginErrorOneOf5) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf5.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf5 from JS object
                this.actualInstance = PluginErrorOneOf5.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf5
            errorMessages.push("Failed to construct PluginErrorOneOf5: " + err)
        }

        try {
            if (instance instanceof PluginErrorOneOf6) {
                this.actualInstance = instance;
            } else {
                // plain JS object
                // validate the object
                PluginErrorOneOf6.validateJSON(instance); // throw an exception if no match
                // create PluginErrorOneOf6 from JS object
                this.actualInstance = PluginErrorOneOf6.constructFromObject(instance);
            }
            match++;
        } catch(err) {
            // json data failed to deserialize into PluginErrorOneOf6
            errorMessages.push("Failed to construct PluginErrorOneOf6: " + err)
        }

        if (match > 1) {
            throw new Error("Multiple matches found constructing `PluginError` with oneOf schemas PluginErrorOneOf, PluginErrorOneOf1, PluginErrorOneOf2, PluginErrorOneOf3, PluginErrorOneOf4, PluginErrorOneOf5, PluginErrorOneOf6. Input: " + JSON.stringify(instance));
        } else if (match === 0) {
            this.actualInstance = null; // clear the actual instance in case there are multiple matches
            throw new Error("No match found constructing `PluginError` with oneOf schemas PluginErrorOneOf, PluginErrorOneOf1, PluginErrorOneOf2, PluginErrorOneOf3, PluginErrorOneOf4, PluginErrorOneOf5, PluginErrorOneOf6. Details: " +
                            errorMessages.join(", "));
        } else { // only 1 match
            // the input is valid
        }
    }

    /**
     * Constructs a <code>PluginError</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PluginError} obj Optional instance to populate.
     * @return {module:model/PluginError} The populated <code>PluginError</code> instance.
     */
    static constructFromObject(data, obj) {
        return new PluginError(data);
    }

    /**
     * Gets the actual instance, which can be <code>PluginErrorOneOf</code>, <code>PluginErrorOneOf1</code>, <code>PluginErrorOneOf2</code>, <code>PluginErrorOneOf3</code>, <code>PluginErrorOneOf4</code>, <code>PluginErrorOneOf5</code>, <code>PluginErrorOneOf6</code>.
     * @return {(module:model/PluginErrorOneOf|module:model/PluginErrorOneOf1|module:model/PluginErrorOneOf2|module:model/PluginErrorOneOf3|module:model/PluginErrorOneOf4|module:model/PluginErrorOneOf5|module:model/PluginErrorOneOf6)} The actual instance.
     */
    getActualInstance() {
        return this.actualInstance;
    }

    /**
     * Sets the actual instance, which can be <code>PluginErrorOneOf</code>, <code>PluginErrorOneOf1</code>, <code>PluginErrorOneOf2</code>, <code>PluginErrorOneOf3</code>, <code>PluginErrorOneOf4</code>, <code>PluginErrorOneOf5</code>, <code>PluginErrorOneOf6</code>.
     * @param {(module:model/PluginErrorOneOf|module:model/PluginErrorOneOf1|module:model/PluginErrorOneOf2|module:model/PluginErrorOneOf3|module:model/PluginErrorOneOf4|module:model/PluginErrorOneOf5|module:model/PluginErrorOneOf6)} obj The actual instance.
     */
    setActualInstance(obj) {
       this.actualInstance = PluginError.constructFromObject(obj).getActualInstance();
    }

    /**
     * Returns the JSON representation of the actual instance.
     * @return {string}
     */
    toJSON = function(){
        return this.getActualInstance();
    }

    /**
     * Create an instance of PluginError from a JSON string.
     * @param {string} json_string JSON string.
     * @return {module:model/PluginError} An instance of PluginError.
     */
    static fromJSON = function(json_string){
        return PluginError.constructFromObject(JSON.parse(json_string));
    }
}

/**
 * @member {Array.<Object>} BadRequest
 */
PluginError.prototype['BadRequest'] = undefined;

/**
 * @member {Array.<Object>} NotFound
 */
PluginError.prototype['NotFound'] = undefined;

/**
 * @member {Array.<Object>} Unauthorized
 */
PluginError.prototype['Unauthorized'] = undefined;

/**
 * @member {Array.<Object>} InternalError
 */
PluginError.prototype['InternalError'] = undefined;

/**
 * @member {Array.<Object>} DatabaseError
 */
PluginError.prototype['DatabaseError'] = undefined;

/**
 * @member {Array.<Object>} ValidationError
 */
PluginError.prototype['ValidationError'] = undefined;

/**
 * @member {String} NotImplemented
 */
PluginError.prototype['NotImplemented'] = undefined;


PluginError.OneOf = ["PluginErrorOneOf", "PluginErrorOneOf1", "PluginErrorOneOf2", "PluginErrorOneOf3", "PluginErrorOneOf4", "PluginErrorOneOf5", "PluginErrorOneOf6"];

export default PluginError;

