/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PluginPricingOneOf1 model module.
 * @module model/PluginPricingOneOf1
 * @version 0.1.0
 */
class PluginPricingOneOf1 {
    /**
     * Constructs a new <code>PluginPricingOneOf1</code>.
     * @alias module:model/PluginPricingOneOf1
     * @param price {Number} 
     * @param type {module:model/PluginPricingOneOf1.TypeEnum} 
     */
    constructor(price, type) { 
        
        PluginPricingOneOf1.initialize(this, price, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, price, type) { 
        obj['price'] = price;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>PluginPricingOneOf1</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PluginPricingOneOf1} obj Optional instance to populate.
     * @return {module:model/PluginPricingOneOf1} The populated <code>PluginPricingOneOf1</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PluginPricingOneOf1();

            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PluginPricingOneOf1</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PluginPricingOneOf1</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PluginPricingOneOf1.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['type'] && !(typeof data['type'] === 'string' || data['type'] instanceof String)) {
            throw new Error("Expected the field `type` to be a primitive type in the JSON string but got " + data['type']);
        }

        return true;
    }


}

PluginPricingOneOf1.RequiredProperties = ["price", "type"];

/**
 * @member {Number} price
 */
PluginPricingOneOf1.prototype['price'] = undefined;

/**
 * @member {module:model/PluginPricingOneOf1.TypeEnum} type
 */
PluginPricingOneOf1.prototype['type'] = undefined;





/**
 * Allowed values for the <code>type</code> property.
 * @enum {String}
 * @readonly
 */
PluginPricingOneOf1['TypeEnum'] = {

    /**
     * value: "one_time"
     * @const
     */
    "one_time": "one_time"
};



export default PluginPricingOneOf1;

