/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ProductVariant model module.
 * @module model/ProductVariant
 * @version 0.1.0
 */
class ProductVariant {
    /**
     * Constructs a new <code>ProductVariant</code>.
     * @alias module:model/ProductVariant
     * @param productId {String} The parent product this variant belongs to. References the product entity.
     * @param sku {String} Variant-specific SKU (must be unique per tenant).
     */
    constructor(productId, sku) { 
        
        ProductVariant.initialize(this, productId, sku);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, sku) { 
        obj['productId'] = productId;
        obj['sku'] = sku;
    }

    /**
     * Constructs a <code>ProductVariant</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductVariant} obj Optional instance to populate.
     * @return {module:model/ProductVariant} The populated <code>ProductVariant</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductVariant();

            if (data.hasOwnProperty('barcode')) {
                obj['barcode'] = ApiClient.convertToType(data['barcode'], 'String');
            }
            if (data.hasOwnProperty('imageLink')) {
                obj['imageLink'] = ApiClient.convertToType(data['imageLink'], 'String');
            }
            if (data.hasOwnProperty('isActive')) {
                obj['isActive'] = ApiClient.convertToType(data['isActive'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('optionValues')) {
                obj['optionValues'] = ApiClient.convertToType(data['optionValues'], Object);
            }
            if (data.hasOwnProperty('price')) {
                obj['price'] = ApiClient.convertToType(data['price'], 'String');
            }
            if (data.hasOwnProperty('priceDelta')) {
                obj['priceDelta'] = ApiClient.convertToType(data['priceDelta'], 'String');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('stockQuantity')) {
                obj['stockQuantity'] = ApiClient.convertToType(data['stockQuantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductVariant</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductVariant</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ProductVariant.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['barcode'] && !(typeof data['barcode'] === 'string' || data['barcode'] instanceof String)) {
            throw new Error("Expected the field `barcode` to be a primitive type in the JSON string but got " + data['barcode']);
        }
        // ensure the json data is a string
        if (data['imageLink'] && !(typeof data['imageLink'] === 'string' || data['imageLink'] instanceof String)) {
            throw new Error("Expected the field `imageLink` to be a primitive type in the JSON string but got " + data['imageLink']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is a string
        if (data['price'] && !(typeof data['price'] === 'string' || data['price'] instanceof String)) {
            throw new Error("Expected the field `price` to be a primitive type in the JSON string but got " + data['price']);
        }
        // ensure the json data is a string
        if (data['priceDelta'] && !(typeof data['priceDelta'] === 'string' || data['priceDelta'] instanceof String)) {
            throw new Error("Expected the field `priceDelta` to be a primitive type in the JSON string but got " + data['priceDelta']);
        }
        // ensure the json data is a string
        if (data['productId'] && !(typeof data['productId'] === 'string' || data['productId'] instanceof String)) {
            throw new Error("Expected the field `productId` to be a primitive type in the JSON string but got " + data['productId']);
        }
        // ensure the json data is a string
        if (data['sku'] && !(typeof data['sku'] === 'string' || data['sku'] instanceof String)) {
            throw new Error("Expected the field `sku` to be a primitive type in the JSON string but got " + data['sku']);
        }

        return true;
    }


}

ProductVariant.RequiredProperties = ["productId", "sku"];

/**
 * @member {String} barcode
 */
ProductVariant.prototype['barcode'] = undefined;

/**
 * @member {String} imageLink
 */
ProductVariant.prototype['imageLink'] = undefined;

/**
 * @member {Boolean} isActive
 */
ProductVariant.prototype['isActive'] = undefined;

/**
 * Human-readable variant label, e.g. \"Red / M\".
 * @member {String} name
 */
ProductVariant.prototype['name'] = undefined;

/**
 * Option name → value map, e.g. `{\"Color\": \"Red\", \"Size\": \"M\"}`.
 * @member {Object} optionValues
 */
ProductVariant.prototype['optionValues'] = undefined;

/**
 * Explicit override price for this variant (takes precedence over parent price + delta).
 * @member {String} price
 */
ProductVariant.prototype['price'] = undefined;

/**
 * Price adjustment relative to the parent product's `default_price`.
 * @member {String} priceDelta
 */
ProductVariant.prototype['priceDelta'] = undefined;

/**
 * The parent product this variant belongs to. References the product entity.
 * @member {String} productId
 */
ProductVariant.prototype['productId'] = undefined;

/**
 * Variant-specific SKU (must be unique per tenant).
 * @member {String} sku
 */
ProductVariant.prototype['sku'] = undefined;

/**
 * Variant-level stock (optional — may be tracked on the parent only).
 * @member {Number} stockQuantity
 */
ProductVariant.prototype['stockQuantity'] = undefined;






export default ProductVariant;

