/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicDeliveryAppointmentStatusResponse model module.
 * @module model/PublicDeliveryAppointmentStatusResponse
 * @version 0.1.0
 */
class PublicDeliveryAppointmentStatusResponse {
    /**
     * Constructs a new <code>PublicDeliveryAppointmentStatusResponse</code>.
     * @alias module:model/PublicDeliveryAppointmentStatusResponse
     * @param appointmentId {String} 
     * @param requestedDate {Date} 
     * @param status {String} 
     * @param warehouseName {String} 
     */
    constructor(appointmentId, requestedDate, status, warehouseName) { 
        
        PublicDeliveryAppointmentStatusResponse.initialize(this, appointmentId, requestedDate, status, warehouseName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appointmentId, requestedDate, status, warehouseName) { 
        obj['appointmentId'] = appointmentId;
        obj['requestedDate'] = requestedDate;
        obj['status'] = status;
        obj['warehouseName'] = warehouseName;
    }

    /**
     * Constructs a <code>PublicDeliveryAppointmentStatusResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicDeliveryAppointmentStatusResponse} obj Optional instance to populate.
     * @return {module:model/PublicDeliveryAppointmentStatusResponse} The populated <code>PublicDeliveryAppointmentStatusResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicDeliveryAppointmentStatusResponse();

            if (data.hasOwnProperty('appointmentId')) {
                obj['appointmentId'] = ApiClient.convertToType(data['appointmentId'], 'String');
            }
            if (data.hasOwnProperty('requestedDate')) {
                obj['requestedDate'] = ApiClient.convertToType(data['requestedDate'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('timeSlot')) {
                obj['timeSlot'] = ApiClient.convertToType(data['timeSlot'], 'String');
            }
            if (data.hasOwnProperty('warehouseName')) {
                obj['warehouseName'] = ApiClient.convertToType(data['warehouseName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PublicDeliveryAppointmentStatusResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PublicDeliveryAppointmentStatusResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PublicDeliveryAppointmentStatusResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['appointmentId'] && !(typeof data['appointmentId'] === 'string' || data['appointmentId'] instanceof String)) {
            throw new Error("Expected the field `appointmentId` to be a primitive type in the JSON string but got " + data['appointmentId']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['timeSlot'] && !(typeof data['timeSlot'] === 'string' || data['timeSlot'] instanceof String)) {
            throw new Error("Expected the field `timeSlot` to be a primitive type in the JSON string but got " + data['timeSlot']);
        }
        // ensure the json data is a string
        if (data['warehouseName'] && !(typeof data['warehouseName'] === 'string' || data['warehouseName'] instanceof String)) {
            throw new Error("Expected the field `warehouseName` to be a primitive type in the JSON string but got " + data['warehouseName']);
        }

        return true;
    }


}

PublicDeliveryAppointmentStatusResponse.RequiredProperties = ["appointmentId", "requestedDate", "status", "warehouseName"];

/**
 * @member {String} appointmentId
 */
PublicDeliveryAppointmentStatusResponse.prototype['appointmentId'] = undefined;

/**
 * @member {Date} requestedDate
 */
PublicDeliveryAppointmentStatusResponse.prototype['requestedDate'] = undefined;

/**
 * @member {String} status
 */
PublicDeliveryAppointmentStatusResponse.prototype['status'] = undefined;

/**
 * @member {String} timeSlot
 */
PublicDeliveryAppointmentStatusResponse.prototype['timeSlot'] = undefined;

/**
 * @member {String} warehouseName
 */
PublicDeliveryAppointmentStatusResponse.prototype['warehouseName'] = undefined;






export default PublicDeliveryAppointmentStatusResponse;

