/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PublicDeliveryAppointmentResponse model module.
 * @module model/PublicDeliveryAppointmentResponse
 * @version 0.1.0
 */
class PublicDeliveryAppointmentResponse {
    /**
     * Constructs a new <code>PublicDeliveryAppointmentResponse</code>.
     * @alias module:model/PublicDeliveryAppointmentResponse
     * @param appointmentId {String} 
     * @param confirmationHint {String} Carries the status-check token (email is out of scope for now).
     * @param message {String} 
     * @param status {String} 
     */
    constructor(appointmentId, confirmationHint, message, status) { 
        
        PublicDeliveryAppointmentResponse.initialize(this, appointmentId, confirmationHint, message, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, appointmentId, confirmationHint, message, status) { 
        obj['appointmentId'] = appointmentId;
        obj['confirmationHint'] = confirmationHint;
        obj['message'] = message;
        obj['status'] = status;
    }

    /**
     * Constructs a <code>PublicDeliveryAppointmentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PublicDeliveryAppointmentResponse} obj Optional instance to populate.
     * @return {module:model/PublicDeliveryAppointmentResponse} The populated <code>PublicDeliveryAppointmentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PublicDeliveryAppointmentResponse();

            if (data.hasOwnProperty('appointmentId')) {
                obj['appointmentId'] = ApiClient.convertToType(data['appointmentId'], 'String');
            }
            if (data.hasOwnProperty('confirmationHint')) {
                obj['confirmationHint'] = ApiClient.convertToType(data['confirmationHint'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PublicDeliveryAppointmentResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PublicDeliveryAppointmentResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PublicDeliveryAppointmentResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['appointmentId'] && !(typeof data['appointmentId'] === 'string' || data['appointmentId'] instanceof String)) {
            throw new Error("Expected the field `appointmentId` to be a primitive type in the JSON string but got " + data['appointmentId']);
        }
        // ensure the json data is a string
        if (data['confirmationHint'] && !(typeof data['confirmationHint'] === 'string' || data['confirmationHint'] instanceof String)) {
            throw new Error("Expected the field `confirmationHint` to be a primitive type in the JSON string but got " + data['confirmationHint']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }

        return true;
    }


}

PublicDeliveryAppointmentResponse.RequiredProperties = ["appointmentId", "confirmationHint", "message", "status"];

/**
 * @member {String} appointmentId
 */
PublicDeliveryAppointmentResponse.prototype['appointmentId'] = undefined;

/**
 * Carries the status-check token (email is out of scope for now).
 * @member {String} confirmationHint
 */
PublicDeliveryAppointmentResponse.prototype['confirmationHint'] = undefined;

/**
 * @member {String} message
 */
PublicDeliveryAppointmentResponse.prototype['message'] = undefined;

/**
 * @member {String} status
 */
PublicDeliveryAppointmentResponse.prototype['status'] = undefined;






export default PublicDeliveryAppointmentResponse;

