/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QRCodeResponse model module.
 * @module model/QRCodeResponse
 * @version 0.1.0
 */
class QRCodeResponse {
    /**
     * Constructs a new <code>QRCodeResponse</code>.
     * @alias module:model/QRCodeResponse
     * @param contentType {String} 
     * @param qrCodeBase64 {String} 
     */
    constructor(contentType, qrCodeBase64) { 
        
        QRCodeResponse.initialize(this, contentType, qrCodeBase64);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, contentType, qrCodeBase64) { 
        obj['content_type'] = contentType;
        obj['qr_code_base64'] = qrCodeBase64;
    }

    /**
     * Constructs a <code>QRCodeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QRCodeResponse} obj Optional instance to populate.
     * @return {module:model/QRCodeResponse} The populated <code>QRCodeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QRCodeResponse();

            if (data.hasOwnProperty('content_type')) {
                obj['content_type'] = ApiClient.convertToType(data['content_type'], 'String');
            }
            if (data.hasOwnProperty('qr_code_base64')) {
                obj['qr_code_base64'] = ApiClient.convertToType(data['qr_code_base64'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QRCodeResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QRCodeResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QRCodeResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['content_type'] && !(typeof data['content_type'] === 'string' || data['content_type'] instanceof String)) {
            throw new Error("Expected the field `content_type` to be a primitive type in the JSON string but got " + data['content_type']);
        }
        // ensure the json data is a string
        if (data['qr_code_base64'] && !(typeof data['qr_code_base64'] === 'string' || data['qr_code_base64'] instanceof String)) {
            throw new Error("Expected the field `qr_code_base64` to be a primitive type in the JSON string but got " + data['qr_code_base64']);
        }

        return true;
    }


}

QRCodeResponse.RequiredProperties = ["content_type", "qr_code_base64"];

/**
 * @member {String} content_type
 */
QRCodeResponse.prototype['content_type'] = undefined;

/**
 * @member {String} qr_code_base64
 */
QRCodeResponse.prototype['qr_code_base64'] = undefined;






export default QRCodeResponse;

