/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReplenishmentSuggestionLine from './ReplenishmentSuggestionLine';

/**
 * The ReplenishmentResponse model module.
 * @module model/ReplenishmentResponse
 * @version 0.1.0
 */
class ReplenishmentResponse {
    /**
     * Constructs a new <code>ReplenishmentResponse</code>.
     * @alias module:model/ReplenishmentResponse
     * @param generatedAt {Date} 
     * @param lines {Array.<module:model/ReplenishmentSuggestionLine>} 
     * @param targetWarehouseId {String} 
     * @param totalSuggestedQuantity {Number} 
     */
    constructor(generatedAt, lines, targetWarehouseId, totalSuggestedQuantity) { 
        
        ReplenishmentResponse.initialize(this, generatedAt, lines, targetWarehouseId, totalSuggestedQuantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, generatedAt, lines, targetWarehouseId, totalSuggestedQuantity) { 
        obj['generatedAt'] = generatedAt;
        obj['lines'] = lines;
        obj['targetWarehouseId'] = targetWarehouseId;
        obj['totalSuggestedQuantity'] = totalSuggestedQuantity;
    }

    /**
     * Constructs a <code>ReplenishmentResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReplenishmentResponse} obj Optional instance to populate.
     * @return {module:model/ReplenishmentResponse} The populated <code>ReplenishmentResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReplenishmentResponse();

            if (data.hasOwnProperty('generatedAt')) {
                obj['generatedAt'] = ApiClient.convertToType(data['generatedAt'], 'Date');
            }
            if (data.hasOwnProperty('lines')) {
                obj['lines'] = ApiClient.convertToType(data['lines'], [ReplenishmentSuggestionLine]);
            }
            if (data.hasOwnProperty('targetWarehouseId')) {
                obj['targetWarehouseId'] = ApiClient.convertToType(data['targetWarehouseId'], 'String');
            }
            if (data.hasOwnProperty('totalSuggestedQuantity')) {
                obj['totalSuggestedQuantity'] = ApiClient.convertToType(data['totalSuggestedQuantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReplenishmentResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReplenishmentResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReplenishmentResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        if (data['lines']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['lines'])) {
                throw new Error("Expected the field `lines` to be an array in the JSON data but got " + data['lines']);
            }
            // validate the optional field `lines` (array)
            for (const item of data['lines']) {
                ReplenishmentSuggestionLine.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['targetWarehouseId'] && !(typeof data['targetWarehouseId'] === 'string' || data['targetWarehouseId'] instanceof String)) {
            throw new Error("Expected the field `targetWarehouseId` to be a primitive type in the JSON string but got " + data['targetWarehouseId']);
        }

        return true;
    }


}

ReplenishmentResponse.RequiredProperties = ["generatedAt", "lines", "targetWarehouseId", "totalSuggestedQuantity"];

/**
 * @member {Date} generatedAt
 */
ReplenishmentResponse.prototype['generatedAt'] = undefined;

/**
 * @member {Array.<module:model/ReplenishmentSuggestionLine>} lines
 */
ReplenishmentResponse.prototype['lines'] = undefined;

/**
 * @member {String} targetWarehouseId
 */
ReplenishmentResponse.prototype['targetWarehouseId'] = undefined;

/**
 * @member {Number} totalSuggestedQuantity
 */
ReplenishmentResponse.prototype['totalSuggestedQuantity'] = undefined;






export default ReplenishmentResponse;

