/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReplenishmentSuggestionLine model module.
 * @module model/ReplenishmentSuggestionLine
 * @version 0.1.0
 */
class ReplenishmentSuggestionLine {
    /**
     * Constructs a new <code>ReplenishmentSuggestionLine</code>.
     * A single replenishment suggestion.
     * @alias module:model/ReplenishmentSuggestionLine
     * @param currentStock {Number} Current stock in the target warehouse.
     * @param productId {String} 
     * @param productName {String} 
     * @param sku {String} 
     * @param sourceAvailable {Number} Surplus available in the source warehouse (above its target).
     * @param sourceWarehouseId {String} 
     * @param suggestedQuantity {Number} 
     * @param targetWarehouseId {String} 
     */
    constructor(currentStock, productId, productName, sku, sourceAvailable, sourceWarehouseId, suggestedQuantity, targetWarehouseId) { 
        
        ReplenishmentSuggestionLine.initialize(this, currentStock, productId, productName, sku, sourceAvailable, sourceWarehouseId, suggestedQuantity, targetWarehouseId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currentStock, productId, productName, sku, sourceAvailable, sourceWarehouseId, suggestedQuantity, targetWarehouseId) { 
        obj['currentStock'] = currentStock;
        obj['productId'] = productId;
        obj['productName'] = productName;
        obj['sku'] = sku;
        obj['sourceAvailable'] = sourceAvailable;
        obj['sourceWarehouseId'] = sourceWarehouseId;
        obj['suggestedQuantity'] = suggestedQuantity;
        obj['targetWarehouseId'] = targetWarehouseId;
    }

    /**
     * Constructs a <code>ReplenishmentSuggestionLine</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReplenishmentSuggestionLine} obj Optional instance to populate.
     * @return {module:model/ReplenishmentSuggestionLine} The populated <code>ReplenishmentSuggestionLine</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReplenishmentSuggestionLine();

            if (data.hasOwnProperty('currentStock')) {
                obj['currentStock'] = ApiClient.convertToType(data['currentStock'], 'Number');
            }
            if (data.hasOwnProperty('maxStock')) {
                obj['maxStock'] = ApiClient.convertToType(data['maxStock'], 'Number');
            }
            if (data.hasOwnProperty('minStock')) {
                obj['minStock'] = ApiClient.convertToType(data['minStock'], 'Number');
            }
            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'String');
            }
            if (data.hasOwnProperty('productName')) {
                obj['productName'] = ApiClient.convertToType(data['productName'], 'String');
            }
            if (data.hasOwnProperty('sku')) {
                obj['sku'] = ApiClient.convertToType(data['sku'], 'String');
            }
            if (data.hasOwnProperty('sourceAvailable')) {
                obj['sourceAvailable'] = ApiClient.convertToType(data['sourceAvailable'], 'Number');
            }
            if (data.hasOwnProperty('sourceWarehouseId')) {
                obj['sourceWarehouseId'] = ApiClient.convertToType(data['sourceWarehouseId'], 'String');
            }
            if (data.hasOwnProperty('suggestedQuantity')) {
                obj['suggestedQuantity'] = ApiClient.convertToType(data['suggestedQuantity'], 'Number');
            }
            if (data.hasOwnProperty('targetWarehouseId')) {
                obj['targetWarehouseId'] = ApiClient.convertToType(data['targetWarehouseId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReplenishmentSuggestionLine</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReplenishmentSuggestionLine</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReplenishmentSuggestionLine.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['productId'] && !(typeof data['productId'] === 'string' || data['productId'] instanceof String)) {
            throw new Error("Expected the field `productId` to be a primitive type in the JSON string but got " + data['productId']);
        }
        // ensure the json data is a string
        if (data['productName'] && !(typeof data['productName'] === 'string' || data['productName'] instanceof String)) {
            throw new Error("Expected the field `productName` to be a primitive type in the JSON string but got " + data['productName']);
        }
        // ensure the json data is a string
        if (data['sku'] && !(typeof data['sku'] === 'string' || data['sku'] instanceof String)) {
            throw new Error("Expected the field `sku` to be a primitive type in the JSON string but got " + data['sku']);
        }
        // ensure the json data is a string
        if (data['sourceWarehouseId'] && !(typeof data['sourceWarehouseId'] === 'string' || data['sourceWarehouseId'] instanceof String)) {
            throw new Error("Expected the field `sourceWarehouseId` to be a primitive type in the JSON string but got " + data['sourceWarehouseId']);
        }
        // ensure the json data is a string
        if (data['targetWarehouseId'] && !(typeof data['targetWarehouseId'] === 'string' || data['targetWarehouseId'] instanceof String)) {
            throw new Error("Expected the field `targetWarehouseId` to be a primitive type in the JSON string but got " + data['targetWarehouseId']);
        }

        return true;
    }


}

ReplenishmentSuggestionLine.RequiredProperties = ["currentStock", "productId", "productName", "sku", "sourceAvailable", "sourceWarehouseId", "suggestedQuantity", "targetWarehouseId"];

/**
 * Current stock in the target warehouse.
 * @member {Number} currentStock
 */
ReplenishmentSuggestionLine.prototype['currentStock'] = undefined;

/**
 * @member {Number} maxStock
 */
ReplenishmentSuggestionLine.prototype['maxStock'] = undefined;

/**
 * @member {Number} minStock
 */
ReplenishmentSuggestionLine.prototype['minStock'] = undefined;

/**
 * @member {String} productId
 */
ReplenishmentSuggestionLine.prototype['productId'] = undefined;

/**
 * @member {String} productName
 */
ReplenishmentSuggestionLine.prototype['productName'] = undefined;

/**
 * @member {String} sku
 */
ReplenishmentSuggestionLine.prototype['sku'] = undefined;

/**
 * Surplus available in the source warehouse (above its target).
 * @member {Number} sourceAvailable
 */
ReplenishmentSuggestionLine.prototype['sourceAvailable'] = undefined;

/**
 * @member {String} sourceWarehouseId
 */
ReplenishmentSuggestionLine.prototype['sourceWarehouseId'] = undefined;

/**
 * @member {Number} suggestedQuantity
 */
ReplenishmentSuggestionLine.prototype['suggestedQuantity'] = undefined;

/**
 * @member {String} targetWarehouseId
 */
ReplenishmentSuggestionLine.prototype['targetWarehouseId'] = undefined;






export default ReplenishmentSuggestionLine;

