/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StockTransferStatus from './StockTransferStatus';

/**
 * The StockTransfer model module.
 * @module model/StockTransfer
 * @version 0.1.0
 */
class StockTransfer {
    /**
     * Constructs a new <code>StockTransfer</code>.
     * @alias module:model/StockTransfer
     * @param lineItems {Object} JSON array of `{product_id, name, quantity, batch_number?}`.
     * @param sourceWarehouseId {String} References the warehouse entity.
     * @param status {module:model/StockTransferStatus} One of: draft | completed | cancelled
     * @param targetWarehouseId {String} References the warehouse entity.
     * @param transferDate {Date} 
     * @param transferNumber {String} 
     */
    constructor(lineItems, sourceWarehouseId, status, targetWarehouseId, transferDate, transferNumber) { 
        
        StockTransfer.initialize(this, lineItems, sourceWarehouseId, status, targetWarehouseId, transferDate, transferNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, lineItems, sourceWarehouseId, status, targetWarehouseId, transferDate, transferNumber) { 
        obj['lineItems'] = lineItems;
        obj['sourceWarehouseId'] = sourceWarehouseId;
        obj['status'] = status;
        obj['targetWarehouseId'] = targetWarehouseId;
        obj['transferDate'] = transferDate;
        obj['transferNumber'] = transferNumber;
    }

    /**
     * Constructs a <code>StockTransfer</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/StockTransfer} obj Optional instance to populate.
     * @return {module:model/StockTransfer} The populated <code>StockTransfer</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StockTransfer();

            if (data.hasOwnProperty('lineItems')) {
                obj['lineItems'] = ApiClient.convertToType(data['lineItems'], Object);
            }
            if (data.hasOwnProperty('notes')) {
                obj['notes'] = ApiClient.convertToType(data['notes'], 'String');
            }
            if (data.hasOwnProperty('sourceWarehouseId')) {
                obj['sourceWarehouseId'] = ApiClient.convertToType(data['sourceWarehouseId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], StockTransferStatus);
            }
            if (data.hasOwnProperty('targetWarehouseId')) {
                obj['targetWarehouseId'] = ApiClient.convertToType(data['targetWarehouseId'], 'String');
            }
            if (data.hasOwnProperty('transferDate')) {
                obj['transferDate'] = ApiClient.convertToType(data['transferDate'], 'Date');
            }
            if (data.hasOwnProperty('transferNumber')) {
                obj['transferNumber'] = ApiClient.convertToType(data['transferNumber'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>StockTransfer</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>StockTransfer</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of StockTransfer.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['notes'] && !(typeof data['notes'] === 'string' || data['notes'] instanceof String)) {
            throw new Error("Expected the field `notes` to be a primitive type in the JSON string but got " + data['notes']);
        }
        // ensure the json data is a string
        if (data['sourceWarehouseId'] && !(typeof data['sourceWarehouseId'] === 'string' || data['sourceWarehouseId'] instanceof String)) {
            throw new Error("Expected the field `sourceWarehouseId` to be a primitive type in the JSON string but got " + data['sourceWarehouseId']);
        }
        // ensure the json data is a string
        if (data['targetWarehouseId'] && !(typeof data['targetWarehouseId'] === 'string' || data['targetWarehouseId'] instanceof String)) {
            throw new Error("Expected the field `targetWarehouseId` to be a primitive type in the JSON string but got " + data['targetWarehouseId']);
        }
        // ensure the json data is a string
        if (data['transferNumber'] && !(typeof data['transferNumber'] === 'string' || data['transferNumber'] instanceof String)) {
            throw new Error("Expected the field `transferNumber` to be a primitive type in the JSON string but got " + data['transferNumber']);
        }

        return true;
    }


}

StockTransfer.RequiredProperties = ["lineItems", "sourceWarehouseId", "status", "targetWarehouseId", "transferDate", "transferNumber"];

/**
 * JSON array of `{product_id, name, quantity, batch_number?}`.
 * @member {Object} lineItems
 */
StockTransfer.prototype['lineItems'] = undefined;

/**
 * @member {String} notes
 */
StockTransfer.prototype['notes'] = undefined;

/**
 * References the warehouse entity.
 * @member {String} sourceWarehouseId
 */
StockTransfer.prototype['sourceWarehouseId'] = undefined;

/**
 * One of: draft | completed | cancelled
 * @member {module:model/StockTransferStatus} status
 */
StockTransfer.prototype['status'] = undefined;

/**
 * References the warehouse entity.
 * @member {String} targetWarehouseId
 */
StockTransfer.prototype['targetWarehouseId'] = undefined;

/**
 * @member {Date} transferDate
 */
StockTransfer.prototype['transferDate'] = undefined;

/**
 * @member {String} transferNumber
 */
StockTransfer.prototype['transferNumber'] = undefined;






export default StockTransfer;

