/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SubmitResultResponse model module.
 * @module model/SubmitResultResponse
 * @version 0.1.0
 */
class SubmitResultResponse {
    /**
     * Constructs a new <code>SubmitResultResponse</code>.
     * @alias module:model/SubmitResultResponse
     * @param completionId {String} 
     * @param passScore {Number} 
     * @param passed {Boolean} 
     * @param score {Number} 
     */
    constructor(completionId, passScore, passed, score) { 
        
        SubmitResultResponse.initialize(this, completionId, passScore, passed, score);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, completionId, passScore, passed, score) { 
        obj['completionId'] = completionId;
        obj['passScore'] = passScore;
        obj['passed'] = passed;
        obj['score'] = score;
    }

    /**
     * Constructs a <code>SubmitResultResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SubmitResultResponse} obj Optional instance to populate.
     * @return {module:model/SubmitResultResponse} The populated <code>SubmitResultResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SubmitResultResponse();

            if (data.hasOwnProperty('certificateId')) {
                obj['certificateId'] = ApiClient.convertToType(data['certificateId'], 'String');
            }
            if (data.hasOwnProperty('completionId')) {
                obj['completionId'] = ApiClient.convertToType(data['completionId'], 'String');
            }
            if (data.hasOwnProperty('passScore')) {
                obj['passScore'] = ApiClient.convertToType(data['passScore'], 'Number');
            }
            if (data.hasOwnProperty('passed')) {
                obj['passed'] = ApiClient.convertToType(data['passed'], 'Boolean');
            }
            if (data.hasOwnProperty('score')) {
                obj['score'] = ApiClient.convertToType(data['score'], 'Number');
            }
            if (data.hasOwnProperty('validUntil')) {
                obj['validUntil'] = ApiClient.convertToType(data['validUntil'], 'Date');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SubmitResultResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SubmitResultResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SubmitResultResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['certificateId'] && !(typeof data['certificateId'] === 'string' || data['certificateId'] instanceof String)) {
            throw new Error("Expected the field `certificateId` to be a primitive type in the JSON string but got " + data['certificateId']);
        }
        // ensure the json data is a string
        if (data['completionId'] && !(typeof data['completionId'] === 'string' || data['completionId'] instanceof String)) {
            throw new Error("Expected the field `completionId` to be a primitive type in the JSON string but got " + data['completionId']);
        }

        return true;
    }


}

SubmitResultResponse.RequiredProperties = ["completionId", "passScore", "passed", "score"];

/**
 * @member {String} certificateId
 */
SubmitResultResponse.prototype['certificateId'] = undefined;

/**
 * @member {String} completionId
 */
SubmitResultResponse.prototype['completionId'] = undefined;

/**
 * @member {Number} passScore
 */
SubmitResultResponse.prototype['passScore'] = undefined;

/**
 * @member {Boolean} passed
 */
SubmitResultResponse.prototype['passed'] = undefined;

/**
 * @member {Number} score
 */
SubmitResultResponse.prototype['score'] = undefined;

/**
 * @member {Date} validUntil
 */
SubmitResultResponse.prototype['validUntil'] = undefined;






export default SubmitResultResponse;

