/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SyncLog model module.
 * @module model/SyncLog
 * @version 0.1.0
 */
class SyncLog {
    /**
     * Constructs a new <code>SyncLog</code>.
     * @alias module:model/SyncLog
     * @param connectionId {String} 
     * @param itemsFailed {Number} 
     * @param itemsSynced {Number} 
     * @param logId {String} 
     * @param platform {String} 
     * @param startedAt {Date} 
     * @param status {String} 
     * @param syncType {String} 
     */
    constructor(connectionId, itemsFailed, itemsSynced, logId, platform, startedAt, status, syncType) { 
        
        SyncLog.initialize(this, connectionId, itemsFailed, itemsSynced, logId, platform, startedAt, status, syncType);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, connectionId, itemsFailed, itemsSynced, logId, platform, startedAt, status, syncType) { 
        obj['connection_id'] = connectionId;
        obj['items_failed'] = itemsFailed;
        obj['items_synced'] = itemsSynced;
        obj['log_id'] = logId;
        obj['platform'] = platform;
        obj['started_at'] = startedAt;
        obj['status'] = status;
        obj['sync_type'] = syncType;
    }

    /**
     * Constructs a <code>SyncLog</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SyncLog} obj Optional instance to populate.
     * @return {module:model/SyncLog} The populated <code>SyncLog</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SyncLog();

            if (data.hasOwnProperty('completed_at')) {
                obj['completed_at'] = ApiClient.convertToType(data['completed_at'], 'Date');
            }
            if (data.hasOwnProperty('connection_id')) {
                obj['connection_id'] = ApiClient.convertToType(data['connection_id'], 'String');
            }
            if (data.hasOwnProperty('error_message')) {
                obj['error_message'] = ApiClient.convertToType(data['error_message'], 'String');
            }
            if (data.hasOwnProperty('items_failed')) {
                obj['items_failed'] = ApiClient.convertToType(data['items_failed'], 'Number');
            }
            if (data.hasOwnProperty('items_synced')) {
                obj['items_synced'] = ApiClient.convertToType(data['items_synced'], 'Number');
            }
            if (data.hasOwnProperty('log_id')) {
                obj['log_id'] = ApiClient.convertToType(data['log_id'], 'String');
            }
            if (data.hasOwnProperty('platform')) {
                obj['platform'] = ApiClient.convertToType(data['platform'], 'String');
            }
            if (data.hasOwnProperty('started_at')) {
                obj['started_at'] = ApiClient.convertToType(data['started_at'], 'Date');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('sync_type')) {
                obj['sync_type'] = ApiClient.convertToType(data['sync_type'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SyncLog</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SyncLog</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of SyncLog.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['connection_id'] && !(typeof data['connection_id'] === 'string' || data['connection_id'] instanceof String)) {
            throw new Error("Expected the field `connection_id` to be a primitive type in the JSON string but got " + data['connection_id']);
        }
        // ensure the json data is a string
        if (data['error_message'] && !(typeof data['error_message'] === 'string' || data['error_message'] instanceof String)) {
            throw new Error("Expected the field `error_message` to be a primitive type in the JSON string but got " + data['error_message']);
        }
        // ensure the json data is a string
        if (data['log_id'] && !(typeof data['log_id'] === 'string' || data['log_id'] instanceof String)) {
            throw new Error("Expected the field `log_id` to be a primitive type in the JSON string but got " + data['log_id']);
        }
        // ensure the json data is a string
        if (data['platform'] && !(typeof data['platform'] === 'string' || data['platform'] instanceof String)) {
            throw new Error("Expected the field `platform` to be a primitive type in the JSON string but got " + data['platform']);
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['sync_type'] && !(typeof data['sync_type'] === 'string' || data['sync_type'] instanceof String)) {
            throw new Error("Expected the field `sync_type` to be a primitive type in the JSON string but got " + data['sync_type']);
        }

        return true;
    }


}

SyncLog.RequiredProperties = ["connection_id", "items_failed", "items_synced", "log_id", "platform", "started_at", "status", "sync_type"];

/**
 * @member {Date} completed_at
 */
SyncLog.prototype['completed_at'] = undefined;

/**
 * @member {String} connection_id
 */
SyncLog.prototype['connection_id'] = undefined;

/**
 * @member {String} error_message
 */
SyncLog.prototype['error_message'] = undefined;

/**
 * @member {Number} items_failed
 */
SyncLog.prototype['items_failed'] = undefined;

/**
 * @member {Number} items_synced
 */
SyncLog.prototype['items_synced'] = undefined;

/**
 * @member {String} log_id
 */
SyncLog.prototype['log_id'] = undefined;

/**
 * @member {String} platform
 */
SyncLog.prototype['platform'] = undefined;

/**
 * @member {Date} started_at
 */
SyncLog.prototype['started_at'] = undefined;

/**
 * @member {String} status
 */
SyncLog.prototype['status'] = undefined;

/**
 * @member {String} sync_type
 */
SyncLog.prototype['sync_type'] = undefined;






export default SyncLog;

