/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TaxRateCreate model module.
 * @module model/TaxRateCreate
 * @version 0.1.0
 */
class TaxRateCreate {
    /**
     * Constructs a new <code>TaxRateCreate</code>.
     * @alias module:model/TaxRateCreate
     * @param countryCode {String} ISO 3166-1 alpha-2 country code.
     * @param isDefault {Boolean} Default rate for the country (one per country); fallback for lookups when no dated rate applies.
     * @param name {String} Human name, e.g. \"VAT\".
     * @param ratePercent {Number} Rate in hundredths of a percent: 1900 = 19.00%.
     */
    constructor(countryCode, isDefault, name, ratePercent) { 
        
        TaxRateCreate.initialize(this, countryCode, isDefault, name, ratePercent);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, countryCode, isDefault, name, ratePercent) { 
        obj['countryCode'] = countryCode;
        obj['isDefault'] = isDefault;
        obj['name'] = name;
        obj['ratePercent'] = ratePercent;
    }

    /**
     * Constructs a <code>TaxRateCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TaxRateCreate} obj Optional instance to populate.
     * @return {module:model/TaxRateCreate} The populated <code>TaxRateCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TaxRateCreate();

            if (data.hasOwnProperty('countryCode')) {
                obj['countryCode'] = ApiClient.convertToType(data['countryCode'], 'String');
            }
            if (data.hasOwnProperty('effectiveFrom')) {
                obj['effectiveFrom'] = ApiClient.convertToType(data['effectiveFrom'], 'Date');
            }
            if (data.hasOwnProperty('isDefault')) {
                obj['isDefault'] = ApiClient.convertToType(data['isDefault'], 'Boolean');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('ratePercent')) {
                obj['ratePercent'] = ApiClient.convertToType(data['ratePercent'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TaxRateCreate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TaxRateCreate</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TaxRateCreate.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['countryCode'] && !(typeof data['countryCode'] === 'string' || data['countryCode'] instanceof String)) {
            throw new Error("Expected the field `countryCode` to be a primitive type in the JSON string but got " + data['countryCode']);
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }

        return true;
    }


}

TaxRateCreate.RequiredProperties = ["countryCode", "isDefault", "name", "ratePercent"];

/**
 * ISO 3166-1 alpha-2 country code.
 * @member {String} countryCode
 */
TaxRateCreate.prototype['countryCode'] = undefined;

/**
 * Date this rate took effect; `None` = not date-bound.
 * @member {Date} effectiveFrom
 */
TaxRateCreate.prototype['effectiveFrom'] = undefined;

/**
 * Default rate for the country (one per country); fallback for lookups when no dated rate applies.
 * @member {Boolean} isDefault
 */
TaxRateCreate.prototype['isDefault'] = undefined;

/**
 * Human name, e.g. \"VAT\".
 * @member {String} name
 */
TaxRateCreate.prototype['name'] = undefined;

/**
 * Rate in hundredths of a percent: 1900 = 19.00%.
 * @member {Number} ratePercent
 */
TaxRateCreate.prototype['ratePercent'] = undefined;






export default TaxRateCreate;

