/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import TrackingEvent from './TrackingEvent';

/**
 * The TrackingInfo model module.
 * @module model/TrackingInfo
 * @version 0.1.0
 */
class TrackingInfo {
    /**
     * Constructs a new <code>TrackingInfo</code>.
     * @alias module:model/TrackingInfo
     * @param carrier {String} 
     * @param events {Array.<module:model/TrackingEvent>} 
     * @param status {String} 
     * @param trackingNumber {String} 
     */
    constructor(carrier, events, status, trackingNumber) { 
        
        TrackingInfo.initialize(this, carrier, events, status, trackingNumber);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, carrier, events, status, trackingNumber) { 
        obj['carrier'] = carrier;
        obj['events'] = events;
        obj['status'] = status;
        obj['tracking_number'] = trackingNumber;
    }

    /**
     * Constructs a <code>TrackingInfo</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TrackingInfo} obj Optional instance to populate.
     * @return {module:model/TrackingInfo} The populated <code>TrackingInfo</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TrackingInfo();

            if (data.hasOwnProperty('carrier')) {
                obj['carrier'] = ApiClient.convertToType(data['carrier'], 'String');
            }
            if (data.hasOwnProperty('estimated_delivery')) {
                obj['estimated_delivery'] = ApiClient.convertToType(data['estimated_delivery'], 'String');
            }
            if (data.hasOwnProperty('events')) {
                obj['events'] = ApiClient.convertToType(data['events'], [TrackingEvent]);
            }
            if (data.hasOwnProperty('raw_response')) {
                obj['raw_response'] = ApiClient.convertToType(data['raw_response'], Object);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('tracking_number')) {
                obj['tracking_number'] = ApiClient.convertToType(data['tracking_number'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>TrackingInfo</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>TrackingInfo</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of TrackingInfo.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['carrier'] && !(typeof data['carrier'] === 'string' || data['carrier'] instanceof String)) {
            throw new Error("Expected the field `carrier` to be a primitive type in the JSON string but got " + data['carrier']);
        }
        // ensure the json data is a string
        if (data['estimated_delivery'] && !(typeof data['estimated_delivery'] === 'string' || data['estimated_delivery'] instanceof String)) {
            throw new Error("Expected the field `estimated_delivery` to be a primitive type in the JSON string but got " + data['estimated_delivery']);
        }
        if (data['events']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['events'])) {
                throw new Error("Expected the field `events` to be an array in the JSON data but got " + data['events']);
            }
            // validate the optional field `events` (array)
            for (const item of data['events']) {
                TrackingEvent.validateJSON(item);
            };
        }
        // ensure the json data is a string
        if (data['status'] && !(typeof data['status'] === 'string' || data['status'] instanceof String)) {
            throw new Error("Expected the field `status` to be a primitive type in the JSON string but got " + data['status']);
        }
        // ensure the json data is a string
        if (data['tracking_number'] && !(typeof data['tracking_number'] === 'string' || data['tracking_number'] instanceof String)) {
            throw new Error("Expected the field `tracking_number` to be a primitive type in the JSON string but got " + data['tracking_number']);
        }

        return true;
    }


}

TrackingInfo.RequiredProperties = ["carrier", "events", "status", "tracking_number"];

/**
 * @member {String} carrier
 */
TrackingInfo.prototype['carrier'] = undefined;

/**
 * @member {String} estimated_delivery
 */
TrackingInfo.prototype['estimated_delivery'] = undefined;

/**
 * @member {Array.<module:model/TrackingEvent>} events
 */
TrackingInfo.prototype['events'] = undefined;

/**
 * @member {Object} raw_response
 */
TrackingInfo.prototype['raw_response'] = undefined;

/**
 * @member {String} status
 */
TrackingInfo.prototype['status'] = undefined;

/**
 * @member {String} tracking_number
 */
TrackingInfo.prototype['tracking_number'] = undefined;






export default TrackingInfo;

