/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EuerDetailErgebnis from '../model/EuerDetailErgebnis';
import EuerErgebnis from '../model/EuerErgebnis';

/**
* Euer service.
* @module api/EuerApi
* @version 0.1.0
*/
export default class EuerApi {

    /**
    * Constructs a new EuerApi. 
    * @alias module:api/EuerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the euerApi operation.
     * @callback module:api/EuerApi~euerApiCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EuerErgebnis} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} year 
     * @param {module:api/EuerApi~euerApiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EuerErgebnis}
     */
    euerApi(year, callback) {
      let postBody = null;
      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling euerApi");
      }

      let pathParams = {
      };
      let queryParams = {
        'year': year
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EuerErgebnis;
      return this.apiClient.callApi(
        '/api/v1/bookkeeping/euer', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the euerKategorienApi operation.
     * @callback module:api/EuerApi~euerKategorienApiCallback
     * @param {String} error Error message, if any.
     * @param {module:model/EuerDetailErgebnis} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} year 
     * @param {module:api/EuerApi~euerKategorienApiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/EuerDetailErgebnis}
     */
    euerKategorienApi(year, callback) {
      let postBody = null;
      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling euerKategorienApi");
      }

      let pathParams = {
      };
      let queryParams = {
        'year': year
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = EuerDetailErgebnis;
      return this.apiClient.callApi(
        '/api/v1/bookkeeping/euer/kategorien', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
