/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GewerbesteuerErgebnis from '../model/GewerbesteuerErgebnis';

/**
* Gewerbesteuer service.
* @module api/GewerbesteuerApi
* @version 0.1.0
*/
export default class GewerbesteuerApi {

    /**
    * Constructs a new GewerbesteuerApi. 
    * @alias module:api/GewerbesteuerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the gewerbesteuerApi operation.
     * @callback module:api/GewerbesteuerApi~gewerbesteuerApiCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GewerbesteuerErgebnis} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Number} year 
     * @param {Object} opts Optional parameters
     * @param {String} [hebesatz] 
     * @param {String} [gewerbeertrag] 
     * @param {String} [country] 
     * @param {String} [gemeindeschluessel] 
     * @param {module:api/GewerbesteuerApi~gewerbesteuerApiCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GewerbesteuerErgebnis}
     */
    gewerbesteuerApi(year, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'year' is set
      if (year === undefined || year === null) {
        throw new Error("Missing the required parameter 'year' when calling gewerbesteuerApi");
      }

      let pathParams = {
      };
      let queryParams = {
        'year': year,
        'hebesatz': opts['hebesatz'],
        'gewerbeertrag': opts['gewerbeertrag'],
        'country': opts['country'],
        'gemeindeschluessel': opts['gemeindeschluessel']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = GewerbesteuerErgebnis;
      return this.apiClient.callApi(
        '/api/v1/bookkeeping/gewerbesteuer', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
