/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import GenerateCountRequest from '../model/GenerateCountRequest';
import InventoryCount from '../model/InventoryCount';
import InventoryCountStatusUpdate from '../model/InventoryCountStatusUpdate';
import PluginError from '../model/PluginError';

/**
* InventoryCount service.
* @module api/InventoryCountApi
* @version 0.1.0
*/
export default class InventoryCountApi {

    /**
    * Constructs a new InventoryCountApi. 
    * @alias module:api/InventoryCountApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createInventoryCount operation.
     * @callback module:api/InventoryCountApi~createInventoryCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryCount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/InventoryCount} inventoryCount 
     * @param {module:api/InventoryCountApi~createInventoryCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryCount}
     */
    createInventoryCount(inventoryCount, callback) {
      let postBody = inventoryCount;
      // verify the required parameter 'inventoryCount' is set
      if (inventoryCount === undefined || inventoryCount === null) {
        throw new Error("Missing the required parameter 'inventoryCount' when calling createInventoryCount");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InventoryCount;
      return this.apiClient.callApi(
        '/api/v1/inventory-counts', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteInventoryCount operation.
     * @callback module:api/InventoryCountApi~deleteInventoryCountCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} inventoryCountId 
     * @param {module:api/InventoryCountApi~deleteInventoryCountCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteInventoryCount(inventoryCountId, callback) {
      let postBody = null;
      // verify the required parameter 'inventoryCountId' is set
      if (inventoryCountId === undefined || inventoryCountId === null) {
        throw new Error("Missing the required parameter 'inventoryCountId' when calling deleteInventoryCount");
      }

      let pathParams = {
        'inventory_count_id': inventoryCountId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/inventory-counts/{inventory_count_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the generateInventoryCount operation.
     * @callback module:api/InventoryCountApi~generateInventoryCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryCount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/GenerateCountRequest} generateCountRequest 
     * @param {module:api/InventoryCountApi~generateInventoryCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryCount}
     */
    generateInventoryCount(generateCountRequest, callback) {
      let postBody = generateCountRequest;
      // verify the required parameter 'generateCountRequest' is set
      if (generateCountRequest === undefined || generateCountRequest === null) {
        throw new Error("Missing the required parameter 'generateCountRequest' when calling generateInventoryCount");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InventoryCount;
      return this.apiClient.callApi(
        '/api/v1/inventory-counts/generate', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getInventoryCount operation.
     * @callback module:api/InventoryCountApi~getInventoryCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryCount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} inventoryCountId 
     * @param {module:api/InventoryCountApi~getInventoryCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryCount}
     */
    getInventoryCount(inventoryCountId, callback) {
      let postBody = null;
      // verify the required parameter 'inventoryCountId' is set
      if (inventoryCountId === undefined || inventoryCountId === null) {
        throw new Error("Missing the required parameter 'inventoryCountId' when calling getInventoryCount");
      }

      let pathParams = {
        'inventory_count_id': inventoryCountId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = InventoryCount;
      return this.apiClient.callApi(
        '/api/v1/inventory-counts/{inventory_count_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listInventoryCounts operation.
     * @callback module:api/InventoryCountApi~listInventoryCountsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/InventoryCount>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {Number} [pageSize] 
     * @param {String} [status] 
     * @param {String} [warehouseId] 
     * @param {module:api/InventoryCountApi~listInventoryCountsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/InventoryCount>}
     */
    listInventoryCounts(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'page_size': opts['pageSize'],
        'status': opts['status'],
        'warehouse_id': opts['warehouseId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [InventoryCount];
      return this.apiClient.callApi(
        '/api/v1/inventory-counts/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateInventoryCount operation.
     * @callback module:api/InventoryCountApi~updateInventoryCountCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryCount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} inventoryCountId 
     * @param {Object} body 
     * @param {module:api/InventoryCountApi~updateInventoryCountCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryCount}
     */
    updateInventoryCount(inventoryCountId, body, callback) {
      let postBody = body;
      // verify the required parameter 'inventoryCountId' is set
      if (inventoryCountId === undefined || inventoryCountId === null) {
        throw new Error("Missing the required parameter 'inventoryCountId' when calling updateInventoryCount");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateInventoryCount");
      }

      let pathParams = {
        'inventory_count_id': inventoryCountId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InventoryCount;
      return this.apiClient.callApi(
        '/api/v1/inventory-counts/{inventory_count_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateInventoryCountStatus operation.
     * @callback module:api/InventoryCountApi~updateInventoryCountStatusCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InventoryCount} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} inventoryCountId 
     * @param {module:model/InventoryCountStatusUpdate} inventoryCountStatusUpdate 
     * @param {module:api/InventoryCountApi~updateInventoryCountStatusCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InventoryCount}
     */
    updateInventoryCountStatus(inventoryCountId, inventoryCountStatusUpdate, callback) {
      let postBody = inventoryCountStatusUpdate;
      // verify the required parameter 'inventoryCountId' is set
      if (inventoryCountId === undefined || inventoryCountId === null) {
        throw new Error("Missing the required parameter 'inventoryCountId' when calling updateInventoryCountStatus");
      }
      // verify the required parameter 'inventoryCountStatusUpdate' is set
      if (inventoryCountStatusUpdate === undefined || inventoryCountStatusUpdate === null) {
        throw new Error("Missing the required parameter 'inventoryCountStatusUpdate' when calling updateInventoryCountStatus");
      }

      let pathParams = {
        'inventory_count_id': inventoryCountId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = InventoryCount;
      return this.apiClient.callApi(
        '/api/v1/inventory-counts/{inventory_count_id}/status', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
