/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PluginError from '../model/PluginError';
import PostingCategory from '../model/PostingCategory';

/**
* PostingCategory service.
* @module api/PostingCategoryApi
* @version 0.1.0
*/
export default class PostingCategoryApi {

    /**
    * Constructs a new PostingCategoryApi. 
    * @alias module:api/PostingCategoryApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createPostingCategory operation.
     * @callback module:api/PostingCategoryApi~createPostingCategoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostingCategory} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} body 
     * @param {module:api/PostingCategoryApi~createPostingCategoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostingCategory}
     */
    createPostingCategory(body, callback) {
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createPostingCategory");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostingCategory;
      return this.apiClient.callApi(
        '/api/v1/posting-categories', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deletePostingCategory operation.
     * @callback module:api/PostingCategoryApi~deletePostingCategoryCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} categoryId 
     * @param {module:api/PostingCategoryApi~deletePostingCategoryCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deletePostingCategory(categoryId, callback) {
      let postBody = null;
      // verify the required parameter 'categoryId' is set
      if (categoryId === undefined || categoryId === null) {
        throw new Error("Missing the required parameter 'categoryId' when calling deletePostingCategory");
      }

      let pathParams = {
        'category_id': categoryId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/posting-categories/{category_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listPostingCategories operation.
     * @callback module:api/PostingCategoryApi~listPostingCategoriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/PostingCategory>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:api/PostingCategoryApi~listPostingCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/PostingCategory>}
     */
    listPostingCategories(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [PostingCategory];
      return this.apiClient.callApi(
        '/api/v1/posting-categories', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the seedPostingCategories operation.
     * @callback module:api/PostingCategoryApi~seedPostingCategoriesCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} skrVersion 
     * @param {module:api/PostingCategoryApi~seedPostingCategoriesCallback} callback The callback function, accepting three arguments: error, data, response
     */
    seedPostingCategories(skrVersion, callback) {
      let postBody = null;
      // verify the required parameter 'skrVersion' is set
      if (skrVersion === undefined || skrVersion === null) {
        throw new Error("Missing the required parameter 'skrVersion' when calling seedPostingCategories");
      }

      let pathParams = {
        'skr_version': skrVersion
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/posting-categories/seed/{skr_version}', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updatePostingCategory operation.
     * @callback module:api/PostingCategoryApi~updatePostingCategoryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/PostingCategory} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} categoryId 
     * @param {Object} body 
     * @param {module:api/PostingCategoryApi~updatePostingCategoryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/PostingCategory}
     */
    updatePostingCategory(categoryId, body, callback) {
      let postBody = body;
      // verify the required parameter 'categoryId' is set
      if (categoryId === undefined || categoryId === null) {
        throw new Error("Missing the required parameter 'categoryId' when calling updatePostingCategory");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updatePostingCategory");
      }

      let pathParams = {
        'category_id': categoryId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = PostingCategory;
      return this.apiClient.callApi(
        '/api/v1/posting-categories/{category_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
