/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import LaborCostRow from '../model/LaborCostRow';
import PluginError from '../model/PluginError';
import TimeEntryClockIn from '../model/TimeEntryClockIn';
import TimeEntryClockOut from '../model/TimeEntryClockOut';
import TimeEntryDto from '../model/TimeEntryDto';

/**
* TimeEntries service.
* @module api/TimeEntriesApi
* @version 0.1.0
*/
export default class TimeEntriesApi {

    /**
    * Constructs a new TimeEntriesApi. 
    * @alias module:api/TimeEntriesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the clockInTimeEntry operation.
     * @callback module:api/TimeEntriesApi~clockInTimeEntryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeEntryDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Clock in for the authenticated user (resolved via their employee profile).
     * @param {module:model/TimeEntryClockIn} timeEntryClockIn 
     * @param {module:api/TimeEntriesApi~clockInTimeEntryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeEntryDto}
     */
    clockInTimeEntry(timeEntryClockIn, callback) {
      let postBody = timeEntryClockIn;
      // verify the required parameter 'timeEntryClockIn' is set
      if (timeEntryClockIn === undefined || timeEntryClockIn === null) {
        throw new Error("Missing the required parameter 'timeEntryClockIn' when calling clockInTimeEntry");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TimeEntryDto;
      return this.apiClient.callApi(
        '/api/v1/time-entries', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the clockOutTimeEntry operation.
     * @callback module:api/TimeEntriesApi~clockOutTimeEntryCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TimeEntryDto} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Clock out an entry: the entry's owner, or anyone with `time_entries:write`.
     * @param {String} id 
     * @param {module:model/TimeEntryClockOut} timeEntryClockOut 
     * @param {module:api/TimeEntriesApi~clockOutTimeEntryCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TimeEntryDto}
     */
    clockOutTimeEntry(id, timeEntryClockOut, callback) {
      let postBody = timeEntryClockOut;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling clockOutTimeEntry");
      }
      // verify the required parameter 'timeEntryClockOut' is set
      if (timeEntryClockOut === undefined || timeEntryClockOut === null) {
        throw new Error("Missing the required parameter 'timeEntryClockOut' when calling clockOutTimeEntry");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TimeEntryDto;
      return this.apiClient.callApi(
        '/api/v1/time-entries/{id}', 'PATCH',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getLaborCosts operation.
     * @callback module:api/TimeEntriesApi~getLaborCostsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/LaborCostRow>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Labor-cost report: worked hours aggregated per employee / order / day, valued at the employee's hourly cost rate.
     * @param {Date} from 
     * @param {Date} to 
     * @param {String} groupBy One of \"employee\", \"order\" or \"day\".
     * @param {module:api/TimeEntriesApi~getLaborCostsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/LaborCostRow>}
     */
    getLaborCosts(from, to, groupBy, callback) {
      let postBody = null;
      // verify the required parameter 'from' is set
      if (from === undefined || from === null) {
        throw new Error("Missing the required parameter 'from' when calling getLaborCosts");
      }
      // verify the required parameter 'to' is set
      if (to === undefined || to === null) {
        throw new Error("Missing the required parameter 'to' when calling getLaborCosts");
      }
      // verify the required parameter 'groupBy' is set
      if (groupBy === undefined || groupBy === null) {
        throw new Error("Missing the required parameter 'groupBy' when calling getLaborCosts");
      }

      let pathParams = {
      };
      let queryParams = {
        'from': from,
        'to': to,
        'group_by': groupBy
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [LaborCostRow];
      return this.apiClient.callApi(
        '/api/v1/labor-costs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listTimeEntries operation.
     * @callback module:api/TimeEntriesApi~listTimeEntriesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/TimeEntryDto>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List time entries with optional date-range / active / employee filters.
     * @param {Object} opts Optional parameters
     * @param {Date} [from] 
     * @param {Date} [to] 
     * @param {Boolean} [active] Only currently running shifts (clock_in set, clock_out null).
     * @param {String} [employeeId] 
     * @param {module:api/TimeEntriesApi~listTimeEntriesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/TimeEntryDto>}
     */
    listTimeEntries(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'from': opts['from'],
        'to': opts['to'],
        'active': opts['active'],
        'employee_id': opts['employeeId']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [TimeEntryDto];
      return this.apiClient.callApi(
        '/api/v1/time-entries', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
