/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import PluginError from '../model/PluginError';
import Voucher from '../model/Voucher';
import VoucherCreate from '../model/VoucherCreate';

/**
* Voucher service.
* @module api/VoucherApi
* @version 0.1.0
*/
export default class VoucherApi {

    /**
    * Constructs a new VoucherApi. 
    * @alias module:api/VoucherApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createVoucher operation.
     * @callback module:api/VoucherApi~createVoucherCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Voucher} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {module:model/VoucherCreate} voucherCreate 
     * @param {module:api/VoucherApi~createVoucherCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Voucher}
     */
    createVoucher(voucherCreate, callback) {
      let postBody = voucherCreate;
      // verify the required parameter 'voucherCreate' is set
      if (voucherCreate === undefined || voucherCreate === null) {
        throw new Error("Missing the required parameter 'voucherCreate' when calling createVoucher");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Voucher;
      return this.apiClient.callApi(
        '/api/v1/vouchers', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteVoucher operation.
     * @callback module:api/VoucherApi~deleteVoucherCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} voucherId 
     * @param {module:api/VoucherApi~deleteVoucherCallback} callback The callback function, accepting three arguments: error, data, response
     */
    deleteVoucher(voucherId, callback) {
      let postBody = null;
      // verify the required parameter 'voucherId' is set
      if (voucherId === undefined || voucherId === null) {
        throw new Error("Missing the required parameter 'voucherId' when calling deleteVoucher");
      }

      let pathParams = {
        'voucher_id': voucherId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = null;
      return this.apiClient.callApi(
        '/api/v1/vouchers/{voucher_id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the getVoucher operation.
     * @callback module:api/VoucherApi~getVoucherCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Voucher} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} voucherId 
     * @param {module:api/VoucherApi~getVoucherCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Voucher}
     */
    getVoucher(voucherId, callback) {
      let postBody = null;
      // verify the required parameter 'voucherId' is set
      if (voucherId === undefined || voucherId === null) {
        throw new Error("Missing the required parameter 'voucherId' when calling getVoucher");
      }

      let pathParams = {
        'voucher_id': voucherId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Voucher;
      return this.apiClient.callApi(
        '/api/v1/vouchers/{voucher_id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the listVouchers operation.
     * @callback module:api/VoucherApi~listVouchersCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Voucher>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {Object} opts Optional parameters
     * @param {Number} [page] 
     * @param {Number} [pageSize] 
     * @param {String} [voucherType] 
     * @param {String} [voucherStatus] 
     * @param {String} [contactName] 
     * @param {Date} [dateFrom] 
     * @param {Date} [dateTo] 
     * @param {module:api/VoucherApi~listVouchersCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Voucher>}
     */
    listVouchers(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
        'page': opts['page'],
        'page_size': opts['pageSize'],
        'voucher_type': opts['voucherType'],
        'voucher_status': opts['voucherStatus'],
        'contact_name': opts['contactName'],
        'date_from': opts['dateFrom'],
        'date_to': opts['dateTo']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = [Voucher];
      return this.apiClient.callApi(
        '/api/v1/vouchers/', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the updateVoucher operation.
     * @callback module:api/VoucherApi~updateVoucherCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Voucher} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} voucherId 
     * @param {Object} body 
     * @param {module:api/VoucherApi~updateVoucherCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Voucher}
     */
    updateVoucher(voucherId, body, callback) {
      let postBody = body;
      // verify the required parameter 'voucherId' is set
      if (voucherId === undefined || voucherId === null) {
        throw new Error("Missing the required parameter 'voucherId' when calling updateVoucher");
      }
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling updateVoucher");
      }

      let pathParams = {
        'voucher_id': voucherId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = Voucher;
      return this.apiClient.callApi(
        '/api/v1/vouchers/{voucher_id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the voucherRestore operation.
     * @callback module:api/VoucherApi~voucherRestoreCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Voucher} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * @param {String} voucherId 
     * @param {module:api/VoucherApi~voucherRestoreCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Voucher}
     */
    voucherRestore(voucherId, callback) {
      let postBody = null;
      // verify the required parameter 'voucherId' is set
      if (voucherId === undefined || voucherId === null) {
        throw new Error("Missing the required parameter 'voucherId' when calling voucherRestore");
      }

      let pathParams = {
        'voucher_id': voucherId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['bearer_token'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = Voucher;
      return this.apiClient.callApi(
        '/api/v1/vouchers/{voucher_id}/restore', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
