/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.AutomationDto();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('AutomationDto', function() {
    it('should create an instance of AutomationDto', function() {
      // uncomment below and update the code to test AutomationDto
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be.a(SimpleBillyApi.AutomationDto);
    });

    it('should have the property automationKey (base name: "automationKey")', function() {
      // uncomment below and update the code to test the property automationKey
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property config (base name: "config")', function() {
      // uncomment below and update the code to test the property config
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property defaultDay (base name: "defaultDay")', function() {
      // uncomment below and update the code to test the property defaultDay
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property enabled (base name: "enabled")', function() {
      // uncomment below and update the code to test the property enabled
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property kind (base name: "kind")', function() {
      // uncomment below and update the code to test the property kind
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property lastRunAt (base name: "lastRunAt")', function() {
      // uncomment below and update the code to test the property lastRunAt
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property nextRunAt (base name: "nextRunAt")', function() {
      // uncomment below and update the code to test the property nextRunAt
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

    it('should have the property scheduleKind (base name: "scheduleKind")', function() {
      // uncomment below and update the code to test the property scheduleKind
      //var instance = new SimpleBillyApi.AutomationDto();
      //expect(instance).to.be();
    });

  });

}));
