/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.BWASummary();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BWASummary', function() {
    it('should create an instance of BWASummary', function() {
      // uncomment below and update the code to test BWASummary
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be.a(SimpleBillyApi.BWASummary);
    });

    it('should have the property grossProfit (base name: "gross_profit")', function() {
      // uncomment below and update the code to test the property grossProfit
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

    it('should have the property netProfit (base name: "net_profit")', function() {
      // uncomment below and update the code to test the property netProfit
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

    it('should have the property openInvoicesCount (base name: "open_invoices_count")', function() {
      // uncomment below and update the code to test the property openInvoicesCount
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

    it('should have the property openInvoicesTotal (base name: "open_invoices_total")', function() {
      // uncomment below and update the code to test the property openInvoicesTotal
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

    it('should have the property overdueInvoicesCount (base name: "overdue_invoices_count")', function() {
      // uncomment below and update the code to test the property overdueInvoicesCount
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

    it('should have the property overdueInvoicesTotal (base name: "overdue_invoices_total")', function() {
      // uncomment below and update the code to test the property overdueInvoicesTotal
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

    it('should have the property profitMargin (base name: "profit_margin")', function() {
      // uncomment below and update the code to test the property profitMargin
      //var instance = new SimpleBillyApi.BWASummary();
      //expect(instance).to.be();
    });

  });

}));
