/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.Contact();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Contact', function() {
    it('should create an instance of Contact', function() {
      // uncomment below and update the code to test Contact
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be.a(SimpleBillyApi.Contact);
    });

    it('should have the property accountHolder (base name: "account_holder")', function() {
      // uncomment below and update the code to test the property accountHolder
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property acquisitionCost (base name: "acquisition_cost")', function() {
      // uncomment below and update the code to test the property acquisitionCost
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property addressSupplement (base name: "address_supplement")', function() {
      // uncomment below and update the code to test the property addressSupplement
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property attention (base name: "attention")', function() {
      // uncomment below and update the code to test the property attention
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property bankName (base name: "bank_name")', function() {
      // uncomment below and update the code to test the property bankName
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property bic (base name: "bic")', function() {
      // uncomment below and update the code to test the property bic
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property buyerReference (base name: "buyer_reference")', function() {
      // uncomment below and update the code to test the property buyerReference
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property certificateAuthority (base name: "certificate_authority")', function() {
      // uncomment below and update the code to test the property certificateAuthority
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property certificateNumber (base name: "certificate_number")', function() {
      // uncomment below and update the code to test the property certificateNumber
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property certificateParagraph (base name: "certificate_paragraph")', function() {
      // uncomment below and update the code to test the property certificateParagraph
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property certificateValidUntil (base name: "certificate_valid_until")', function() {
      // uncomment below and update the code to test the property certificateValidUntil
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property companyName (base name: "company_name")', function() {
      // uncomment below and update the code to test the property companyName
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property contactId (base name: "contact_id")', function() {
      // uncomment below and update the code to test the property contactId
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property contactPersons (base name: "contact_persons")', function() {
      // uncomment below and update the code to test the property contactPersons
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property contactType (base name: "contact_type")', function() {
      // uncomment below and update the code to test the property contactType
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "created_at")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property creditLimit (base name: "credit_limit")', function() {
      // uncomment below and update the code to test the property creditLimit
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property creditorAccountSkr03 (base name: "creditor_account_skr03")', function() {
      // uncomment below and update the code to test the property creditorAccountSkr03
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property creditorAccountSkr04 (base name: "creditor_account_skr04")', function() {
      // uncomment below and update the code to test the property creditorAccountSkr04
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property customerNumber (base name: "customer_number")', function() {
      // uncomment below and update the code to test the property customerNumber
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property debitorAccountSkr03 (base name: "debitor_account_skr03")', function() {
      // uncomment below and update the code to test the property debitorAccountSkr03
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property debitorAccountSkr04 (base name: "debitor_account_skr04")', function() {
      // uncomment below and update the code to test the property debitorAccountSkr04
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property defaultDebitorNumber (base name: "default_debitor_number")', function() {
      // uncomment below and update the code to test the property defaultDebitorNumber
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property deliveryBlock (base name: "delivery_block")', function() {
      // uncomment below and update the code to test the property deliveryBlock
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property department (base name: "department")', function() {
      // uncomment below and update the code to test the property department
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property discountDays (base name: "discount_days")', function() {
      // uncomment below and update the code to test the property discountDays
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property discountPercentage (base name: "discount_percentage")', function() {
      // uncomment below and update the code to test the property discountPercentage
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property donationReceiptEligible (base name: "donation_receipt_eligible")', function() {
      // uncomment below and update the code to test the property donationReceiptEligible
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property externalId (base name: "external_id")', function() {
      // uncomment below and update the code to test the property externalId
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property fax (base name: "fax")', function() {
      // uncomment below and update the code to test the property fax
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property iban (base name: "iban")', function() {
      // uncomment below and update the code to test the property iban
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property industry (base name: "industry")', function() {
      // uncomment below and update the code to test the property industry
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "is_active")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property isMember (base name: "is_member")', function() {
      // uncomment below and update the code to test the property isMember
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property isNonprofit (base name: "is_nonprofit")', function() {
      // uncomment below and update the code to test the property isNonprofit
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property lastContactDate (base name: "last_contact_date")', function() {
      // uncomment below and update the code to test the property lastContactDate
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property lastPurchaseDate (base name: "last_purchase_date")', function() {
      // uncomment below and update the code to test the property lastPurchaseDate
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property leitwegId (base name: "leitweg_id")', function() {
      // uncomment below and update the code to test the property leitwegId
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property lifetimeValue (base name: "lifetime_value")', function() {
      // uncomment below and update the code to test the property lifetimeValue
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property mandateDate (base name: "mandate_date")', function() {
      // uncomment below and update the code to test the property mandateDate
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property mandateReference (base name: "mandate_reference")', function() {
      // uncomment below and update the code to test the property mandateReference
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property marketingConsent (base name: "marketing_consent")', function() {
      // uncomment below and update the code to test the property marketingConsent
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property marketingConsentAt (base name: "marketing_consent_at")', function() {
      // uncomment below and update the code to test the property marketingConsentAt
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property marketingConsentSource (base name: "marketing_consent_source")', function() {
      // uncomment below and update the code to test the property marketingConsentSource
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property mobile (base name: "mobile")', function() {
      // uncomment below and update the code to test the property mobile
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property nextContactDate (base name: "next_contact_date")', function() {
      // uncomment below and update the code to test the property nextContactDate
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property openingBalance (base name: "opening_balance")', function() {
      // uncomment below and update the code to test the property openingBalance
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property openingBalanceDate (base name: "opening_balance_date")', function() {
      // uncomment below and update the code to test the property openingBalanceDate
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property orderReference (base name: "order_reference")', function() {
      // uncomment below and update the code to test the property orderReference
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property paymentBlock (base name: "payment_block")', function() {
      // uncomment below and update the code to test the property paymentBlock
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property paymentGracePeriodDays (base name: "payment_grace_period_days")', function() {
      // uncomment below and update the code to test the property paymentGracePeriodDays
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property paymentMethods (base name: "payment_methods")', function() {
      // uncomment below and update the code to test the property paymentMethods
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property paymentTerms (base name: "payment_terms")', function() {
      // uncomment below and update the code to test the property paymentTerms
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property rating (base name: "rating")', function() {
      // uncomment below and update the code to test the property rating
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property salesRepresentative (base name: "sales_representative")', function() {
      // uncomment below and update the code to test the property salesRepresentative
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property socialMedia (base name: "social_media")', function() {
      // uncomment below and update the code to test the property socialMedia
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property source (base name: "source")', function() {
      // uncomment below and update the code to test the property source
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property state (base name: "state")', function() {
      // uncomment below and update the code to test the property state
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property street (base name: "street")', function() {
      // uncomment below and update the code to test the property street
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property streetNumber (base name: "street_number")', function() {
      // uncomment below and update the code to test the property streetNumber
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property supplierNumber (base name: "supplier_number")', function() {
      // uncomment below and update the code to test the property supplierNumber
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property tags (base name: "tags")', function() {
      // uncomment below and update the code to test the property tags
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property taxCountry (base name: "tax_country")', function() {
      // uncomment below and update the code to test the property taxCountry
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property taxNumber (base name: "tax_number")', function() {
      // uncomment below and update the code to test the property taxNumber
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property taxOffice (base name: "tax_office")', function() {
      // uncomment below and update the code to test the property taxOffice
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property totalInvoices (base name: "total_invoices")', function() {
      // uncomment below and update the code to test the property totalInvoices
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property totalRevenue (base name: "total_revenue")', function() {
      // uncomment below and update the code to test the property totalRevenue
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updated_at")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property vatId (base name: "vat_id")', function() {
      // uncomment below and update the code to test the property vatId
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property vatIdValidated (base name: "vat_id_validated")', function() {
      // uncomment below and update the code to test the property vatIdValidated
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property vatIdValidationDate (base name: "vat_id_validation_date")', function() {
      // uncomment below and update the code to test the property vatIdValidationDate
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property website (base name: "website")', function() {
      // uncomment below and update the code to test the property website
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

    it('should have the property zip (base name: "zip")', function() {
      // uncomment below and update the code to test the property zip
      //var instance = new SimpleBillyApi.Contact();
      //expect(instance).to.be();
    });

  });

}));
