/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.Coupon();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Coupon', function() {
    it('should create an instance of Coupon', function() {
      // uncomment below and update the code to test Coupon
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be.a(SimpleBillyApi.Coupon);
    });

    it('should have the property code (base name: "code")', function() {
      // uncomment below and update the code to test the property code
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property discountType (base name: "discountType")', function() {
      // uncomment below and update the code to test the property discountType
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property discountValue (base name: "discountValue")', function() {
      // uncomment below and update the code to test the property discountValue
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property expiresAt (base name: "expiresAt")', function() {
      // uncomment below and update the code to test the property expiresAt
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property isActive (base name: "isActive")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property isCombineable (base name: "isCombineable")', function() {
      // uncomment below and update the code to test the property isCombineable
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property maxDiscountAmount (base name: "maxDiscountAmount")', function() {
      // uncomment below and update the code to test the property maxDiscountAmount
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property maxUses (base name: "maxUses")', function() {
      // uncomment below and update the code to test the property maxUses
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property maxUsesPerCustomer (base name: "maxUsesPerCustomer")', function() {
      // uncomment below and update the code to test the property maxUsesPerCustomer
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property minOrderAmount (base name: "minOrderAmount")', function() {
      // uncomment below and update the code to test the property minOrderAmount
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property productIds (base name: "productIds")', function() {
      // uncomment below and update the code to test the property productIds
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

    it('should have the property startsAt (base name: "startsAt")', function() {
      // uncomment below and update the code to test the property startsAt
      //var instance = new SimpleBillyApi.Coupon();
      //expect(instance).to.be();
    });

  });

}));
