/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.EBilanzReport();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EBilanzReport', function() {
    it('should create an instance of EBilanzReport', function() {
      // uncomment below and update the code to test EBilanzReport
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be.a(SimpleBillyApi.EBilanzReport);
    });

    it('should have the property accountOverview (base name: "account_overview")', function() {
      // uncomment below and update the code to test the property accountOverview
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be();
    });

    it('should have the property balanceSheet (base name: "balance_sheet")', function() {
      // uncomment below and update the code to test the property balanceSheet
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be();
    });

    it('should have the property generatedAt (base name: "generated_at")', function() {
      // uncomment below and update the code to test the property generatedAt
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be();
    });

    it('should have the property incomeStatement (base name: "income_statement")', function() {
      // uncomment below and update the code to test the property incomeStatement
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be();
    });

    it('should have the property period (base name: "period")', function() {
      // uncomment below and update the code to test the property period
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be();
    });

    it('should have the property vatSummary (base name: "vat_summary")', function() {
      // uncomment below and update the code to test the property vatSummary
      //var instance = new SimpleBillyApi.EBilanzReport();
      //expect(instance).to.be();
    });

  });

}));
