/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.EksErgebnis();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('EksErgebnis', function() {
    it('should create an instance of EksErgebnis', function() {
      // uncomment below and update the code to test EksErgebnis
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be.a(SimpleBillyApi.EksErgebnis);
    });

    it('should have the property gesamtergebnis (base name: "gesamtergebnis")', function() {
      // uncomment below and update the code to test the property gesamtergebnis
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property monate (base name: "monate")', function() {
      // uncomment below and update the code to test the property monate
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property prognoseNaechste6Monate (base name: "prognose_naechste_6_monate")', function() {
      // uncomment below and update the code to test the property prognoseNaechste6Monate
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property summeAusgaben (base name: "summe_ausgaben")', function() {
      // uncomment below and update the code to test the property summeAusgaben
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property summeEinnahmen (base name: "summe_einnahmen")', function() {
      // uncomment below and update the code to test the property summeEinnahmen
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property zeitraumBis (base name: "zeitraum_bis")', function() {
      // uncomment below and update the code to test the property zeitraumBis
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property zeitraumVon (base name: "zeitraum_von")', function() {
      // uncomment below and update the code to test the property zeitraumVon
      //var instance = new SimpleBillyApi.EksErgebnis();
      //expect(instance).to.be();
    });

  });

}));
