/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.KstErgebnis();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KstErgebnis', function() {
    it('should create an instance of KstErgebnis', function() {
      // uncomment below and update the code to test KstErgebnis
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be.a(SimpleBillyApi.KstErgebnis);
    });

    it('should have the property gesamt (base name: "gesamt")', function() {
      // uncomment below and update the code to test the property gesamt
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property gesamtbelastung (base name: "gesamtbelastung")', function() {
      // uncomment below and update the code to test the property gesamtbelastung
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property gewerbesteuer (base name: "gewerbesteuer")', function() {
      // uncomment below and update the code to test the property gewerbesteuer
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property gewinn (base name: "gewinn")', function() {
      // uncomment below and update the code to test the property gewinn
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property istKapitalgesellschaft (base name: "ist_kapitalgesellschaft")', function() {
      // uncomment below and update the code to test the property istKapitalgesellschaft
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property jahr (base name: "jahr")', function() {
      // uncomment below and update the code to test the property jahr
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property koerperschaftsteuer (base name: "koerperschaftsteuer")', function() {
      // uncomment below and update the code to test the property koerperschaftsteuer
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

    it('should have the property solidaritaetszuschlag (base name: "solidaritaetszuschlag")', function() {
      // uncomment below and update the code to test the property solidaritaetszuschlag
      //var instance = new SimpleBillyApi.KstErgebnis();
      //expect(instance).to.be();
    });

  });

}));
