/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.ShippingThresholdUpdate();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ShippingThresholdUpdate', function() {
    it('should create an instance of ShippingThresholdUpdate', function() {
      // uncomment below and update the code to test ShippingThresholdUpdate
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be.a(SimpleBillyApi.ShippingThresholdUpdate);
    });

    it('should have the property isActive (base name: "isActive")', function() {
      // uncomment below and update the code to test the property isActive
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

    it('should have the property maxSellable (base name: "maxSellable")', function() {
      // uncomment below and update the code to test the property maxSellable
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

    it('should have the property productId (base name: "productId")', function() {
      // uncomment below and update the code to test the property productId
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

    it('should have the property reserveStock (base name: "reserveStock")', function() {
      // uncomment below and update the code to test the property reserveStock
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

    it('should have the property warehouseId (base name: "warehouseId")', function() {
      // uncomment below and update the code to test the property warehouseId
      //var instance = new SimpleBillyApi.ShippingThresholdUpdate();
      //expect(instance).to.be();
    });

  });

}));
