/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.Shipment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Shipment', function() {
    it('should create an instance of Shipment', function() {
      // uncomment below and update the code to test Shipment
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be.a(SimpleBillyApi.Shipment);
    });

    it('should have the property deliveredAt (base name: "deliveredAt")', function() {
      // uncomment below and update the code to test the property deliveredAt
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property labelUrl (base name: "labelUrl")', function() {
      // uncomment below and update the code to test the property labelUrl
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property lineItemsShipment (base name: "lineItemsShipment")', function() {
      // uncomment below and update the code to test the property lineItemsShipment
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property orderId (base name: "orderId")', function() {
      // uncomment below and update the code to test the property orderId
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property recipientAddress (base name: "recipientAddress")', function() {
      // uncomment below and update the code to test the property recipientAddress
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property shipmentDate (base name: "shipmentDate")', function() {
      // uncomment below and update the code to test the property shipmentDate
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property shippingCarrier (base name: "shippingCarrier")', function() {
      // uncomment below and update the code to test the property shippingCarrier
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property shippingCost (base name: "shippingCost")', function() {
      // uncomment below and update the code to test the property shippingCost
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property shippingMethod (base name: "shippingMethod")', function() {
      // uncomment below and update the code to test the property shippingMethod
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property signedBy (base name: "signedBy")', function() {
      // uncomment below and update the code to test the property signedBy
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property trackingEvents (base name: "trackingEvents")', function() {
      // uncomment below and update the code to test the property trackingEvents
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property trackingNumber (base name: "trackingNumber")', function() {
      // uncomment below and update the code to test the property trackingNumber
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property trackingUrl (base name: "trackingUrl")', function() {
      // uncomment below and update the code to test the property trackingUrl
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

    it('should have the property weightKg (base name: "weightKg")', function() {
      // uncomment below and update the code to test the property weightKg
      //var instance = new SimpleBillyApi.Shipment();
      //expect(instance).to.be();
    });

  });

}));
