/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.TrainingAssignment();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TrainingAssignment', function() {
    it('should create an instance of TrainingAssignment', function() {
      // uncomment below and update the code to test TrainingAssignment
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be.a(SimpleBillyApi.TrainingAssignment);
    });

    it('should have the property assignedBy (base name: "assignedBy")', function() {
      // uncomment below and update the code to test the property assignedBy
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property createdAt (base name: "createdAt")', function() {
      // uncomment below and update the code to test the property createdAt
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property deletedAt (base name: "deletedAt")', function() {
      // uncomment below and update the code to test the property deletedAt
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property dueDate (base name: "dueDate")', function() {
      // uncomment below and update the code to test the property dueDate
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property employeeId (base name: "employeeId")', function() {
      // uncomment below and update the code to test the property employeeId
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property tenantId (base name: "tenantId")', function() {
      // uncomment below and update the code to test the property tenantId
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property trainingId (base name: "trainingId")', function() {
      // uncomment below and update the code to test the property trainingId
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

    it('should have the property updatedAt (base name: "updatedAt")', function() {
      // uncomment below and update the code to test the property updatedAt
      //var instance = new SimpleBillyApi.TrainingAssignment();
      //expect(instance).to.be();
    });

  });

}));
