/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.DeliveryAppointmentApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DeliveryAppointmentApi', function() {
    describe('createDeliveryAppointment', function() {
      it('should call createDeliveryAppointment successfully', function(done) {
        //uncomment below and update the code to test createDeliveryAppointment
        //instance.createDeliveryAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteDeliveryAppointment', function() {
      it('should call deleteDeliveryAppointment successfully', function(done) {
        //uncomment below and update the code to test deleteDeliveryAppointment
        //instance.deleteDeliveryAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getDeliveryAppointment', function() {
      it('should call getDeliveryAppointment successfully', function(done) {
        //uncomment below and update the code to test getDeliveryAppointment
        //instance.getDeliveryAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getPublicDeliveryAppointmentStatus', function() {
      it('should call getPublicDeliveryAppointmentStatus successfully', function(done) {
        //uncomment below and update the code to test getPublicDeliveryAppointmentStatus
        //instance.getPublicDeliveryAppointmentStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listDeliveryAppointments', function() {
      it('should call listDeliveryAppointments successfully', function(done) {
        //uncomment below and update the code to test listDeliveryAppointments
        //instance.listDeliveryAppointments(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('requestPublicDeliveryAppointment', function() {
      it('should call requestPublicDeliveryAppointment successfully', function(done) {
        //uncomment below and update the code to test requestPublicDeliveryAppointment
        //instance.requestPublicDeliveryAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDeliveryAppointment', function() {
      it('should call updateDeliveryAppointment successfully', function(done) {
        //uncomment below and update the code to test updateDeliveryAppointment
        //instance.updateDeliveryAppointment(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateDeliveryAppointmentStatus', function() {
      it('should call updateDeliveryAppointmentStatus successfully', function(done) {
        //uncomment below and update the code to test updateDeliveryAppointmentStatus
        //instance.updateDeliveryAppointmentStatus(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
