/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.KycRecordApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('KycRecordApi', function() {
    describe('createKycRecord', function() {
      it('should call createKycRecord successfully', function(done) {
        //uncomment below and update the code to test createKycRecord
        //instance.createKycRecord(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteKycRecord', function() {
      it('should call deleteKycRecord successfully', function(done) {
        //uncomment below and update the code to test deleteKycRecord
        //instance.deleteKycRecord(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getKycRecord', function() {
      it('should call getKycRecord successfully', function(done) {
        //uncomment below and update the code to test getKycRecord
        //instance.getKycRecord(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getKycRecords', function() {
      it('should call getKycRecords successfully', function(done) {
        //uncomment below and update the code to test getKycRecords
        //instance.getKycRecords(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateKycRecord', function() {
      it('should call updateKycRecord successfully', function(done) {
        //uncomment below and update the code to test updateKycRecord
        //instance.updateKycRecord(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
