/**
 * SimpleBilly API
 * Simplebilly API - Bookkeeping, CRM, ERP. Multi-tenant API: a tenant is isolated and routed by subdomain (or a configured custom domain) under the base domain.  ## Rate limiting All endpoints are rate-limited per client IP: **100 requests per minute** on API routes and **5 requests per minute** on authentication routes. Exceeding a limit returns `429 Too Many Requests`; the window resets after 60 seconds.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@simplebilly.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SimpleBillyApi);
  }
}(this, function(expect, SimpleBillyApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SimpleBillyApi.MarketplaceApiApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('MarketplaceApiApi', function() {
    describe('createConnectionApi', function() {
      it('should call createConnectionApi successfully', function(done) {
        //uncomment below and update the code to test createConnectionApi
        //instance.createConnectionApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteConnectionApi', function() {
      it('should call deleteConnectionApi successfully', function(done) {
        //uncomment below and update the code to test deleteConnectionApi
        //instance.deleteConnectionApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getConnectionApi', function() {
      it('should call getConnectionApi successfully', function(done) {
        //uncomment below and update the code to test getConnectionApi
        //instance.getConnectionApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSyncDirectionApi', function() {
      it('should call getSyncDirectionApi successfully', function(done) {
        //uncomment below and update the code to test getSyncDirectionApi
        //instance.getSyncDirectionApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSyncLogsApi', function() {
      it('should call getSyncLogsApi successfully', function(done) {
        //uncomment below and update the code to test getSyncLogsApi
        //instance.getSyncLogsApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listConnectionsApi', function() {
      it('should call listConnectionsApi successfully', function(done) {
        //uncomment below and update the code to test listConnectionsApi
        //instance.listConnectionsApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listPlatformsApi', function() {
      it('should call listPlatformsApi successfully', function(done) {
        //uncomment below and update the code to test listPlatformsApi
        //instance.listPlatformsApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('oauthAuthorizeApi', function() {
      it('should call oauthAuthorizeApi successfully', function(done) {
        //uncomment below and update the code to test oauthAuthorizeApi
        //instance.oauthAuthorizeApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('oauthCallbackApi', function() {
      it('should call oauthCallbackApi successfully', function(done) {
        //uncomment below and update the code to test oauthCallbackApi
        //instance.oauthCallbackApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('triggerSyncApi', function() {
      it('should call triggerSyncApi successfully', function(done) {
        //uncomment below and update the code to test triggerSyncApi
        //instance.triggerSyncApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateConnectionApi', function() {
      it('should call updateConnectionApi successfully', function(done) {
        //uncomment below and update the code to test updateConnectionApi
        //instance.updateConnectionApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateSyncDirectionApi', function() {
      it('should call updateSyncDirectionApi successfully', function(done) {
        //uncomment below and update the code to test updateSyncDirectionApi
        //instance.updateSyncDirectionApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('webhookReceiverApi', function() {
      it('should call webhookReceiverApi successfully', function(done) {
        //uncomment below and update the code to test webhookReceiverApi
        //instance.webhookReceiverApi(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
